# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BundlesV1Exp")

model_instance <- BundlesV1Exp$new()

test_that("current_page", {
  # tests for the property `current_page` (integer)
  # The current page of results.

  # uncomment below to test the property
  #expect_equal(model.instance$`current_page`, "EXPECTED_RESULT")
})

test_that("total", {
  # tests for the property `total` (integer)
  # The total number of bundles that belong to the given content.

  # uncomment below to test the property
  #expect_equal(model.instance$`total`, "EXPECTED_RESULT")
})

test_that("results", {
  # tests for the property `results` (array[BundleV1Exp])
  # The bundles list

  # uncomment below to test the property
  #expect_equal(model.instance$`results`, "EXPECTED_RESULT")
})
