# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Installation")

model_instance <- Installation$new()

test_that("path", {
  # tests for the property `path` (character)
  # The absolute path to the interpreter&#39;s executable.

  # uncomment below to test the property
  #expect_equal(model.instance$`path`, "EXPECTED_RESULT")
})

test_that("version", {
  # tests for the property `version` (character)
  # The semantic version of the interpreter.

  # uncomment below to test the property
  #expect_equal(model.instance$`version`, "EXPECTED_RESULT")
})
