# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test TasksV1ExperimentalApi")

api_instance <- TasksV1ExperimentalApi$new()

test_that("GetTask", {
  # tests for GetTask
  # base path: /__api__
  # Get task details
  # Returns the current state of a task and any output lines past the requested initial position (&#x60;first&#x60;).  When &#x60;wait&#x60; is non-zero, will wait up to that number of seconds for the task to complete before responding. The current state of the task is returned once the task completes or &#x60;wait&#x60; seconds elapse.  Incrementally receive task output by using the &#x60;last&#x60; response field value as the &#x60;first&#x60; value in a subsequent query.  Use &#x60;wait&#x60; and &#x60;first&#x60; together to incrementally fetch generated output.  Here is a URL that allows up to 5 seconds before returning all available output:  &#x60;&#x60;&#x60; /v1/experimental/tasks/CmsfmnfDDyRUrsAc?wait&#x3D;5&amp;first&#x3D;0 &#x60;&#x60;&#x60;  Let&#39;s assume that request has a JSON response with the &#x60;last&#x60; field having a value of &#x60;23&#x60;. Here is a URL that requests output past that point, again allowing up to 5 seconds:  &#x60;&#x60;&#x60; /v1/experimental/tasks/CmsfmnfDDyRUrsAc?wait&#x3D;5&amp;first&#x3D;23 &#x60;&#x60;&#x60;  Continue with this pattern until the JSON response indicates that the task has finished.
  # @param id character The identifier of the desired task.
  # @param first integer The first line of output to include in the response. The value `0` indicates that all lines should be returned.  Values less than `0` are not permitted. Values greater than the total number of lines produced by the task are not permitted. (optional)
  # @param wait integer The number of seconds to wait for task completion before responding. The current state of the task is returned once the task completes or this time elapses.  Values less than `0` or greater than `20` are not permitted. (optional)
  # @return [GetTask200Response]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
