# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CreateGroupRequest")

model_instance <- CreateGroupRequest$new()

test_that("name", {
  # tests for the property `name` (character)
  # The group&#39;s desired name

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("unique_id", {
  # tests for the property `unique_id` (character)
  # Applies to SAML, OAuth2 and Proxied authentication when the setting &#x60;GroupsByUniqueId&#x60; is enabled. This field must not be present otherwise.

  # uncomment below to test the property
  #expect_equal(model.instance$`unique_id`, "EXPECTED_RESULT")
})
