# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AuditLogs")

model_instance <- AuditLogs$new()

test_that("paging", {
  # tests for the property `paging` (AuditPager)

  # uncomment below to test the property
  #expect_equal(model.instance$`paging`, "EXPECTED_RESULT")
})

test_that("results", {
  # tests for the property `results` (array[AuditEntry])
  # The audit logs

  # uncomment below to test the property
  #expect_equal(model.instance$`results`, "EXPECTED_RESULT")
})
