# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ContentApi")

api_instance <- ContentApi$new()

test_that("BuildContentBundle", {
  # tests for BuildContentBundle
  # base path: /__api__
  # Build deployment bundle
  # Build (restore) a deployment bundle.  Build requests spawn an asynchronous task to make your previously uploaded data ready for rendering or running. Content will have its environment reconstructed, e.g. by using the packrat R package to install R package dependencies, but documents will not be re-rendered.  Building is intended to facilitate server changes or migrations that may require re-installing R packages or other dependencies.  The response from this endpoint includes a task identifier. Poll the &lt;a href&#x3D;\&quot;#get-/v1/tasks/-id-\&quot;&gt;GET /v1/tasks/{id}&lt;/a&gt; endpoint to track the progress of this task.
  # @param guid character The unique identifier of the desired content item.
  # @param instructions BuildContentBundleRequest The request body when requesting the building of a specific bundle. (optional)
  # @return [BuildContentBundle200Response]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("CreateContent", {
  # tests for CreateContent
  # base path: /__api__
  # Create content item
  # Create a new content item.  Authenticated access from a user having either \&quot;publisher\&quot; or \&quot;administrator\&quot; role is allowed. All other clients are rejected.
  # @param content CreateContentRequest The request body required when creating a new content item.
  # @return [Content]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeleteContent", {
  # tests for DeleteContent
  # base path: /__api__
  # Delete content
  # Delete a specific content item.  On-disk data and database records are removed as a consequence of this call.
  # @param guid character The unique identifier of the desired content item.
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeployContentBundle", {
  # tests for DeployContentBundle
  # base path: /__api__
  # Deploy deployment bundle
  # Deploy (activate) a deployment bundle.  Deployment requests spawn an asynchronous task to make your previously uploaded data available for serving. The workflow applied to the bundled files varies depending on the type of content.  Executable content has its environment reconstructed. This includes using the packrat R package to install R package dependencies.  Documents (R Markdown reports, Jupyter Notebooks, static Quarto content) are rendered and the result made available.  Interactive content (applications and APIs) are available to be launched on the next client visit.  The deployment workflow for static content (HTML, plots) is lighter-weight than for executable content. File time-stamps are updated to ensure that browsers do not cache previous results and instead see the newly promoted files.  The response from this endpoint includes a task identifier. Poll the &lt;a href&#x3D;\&quot;#get-/v1/tasks/-id-\&quot;&gt;GET /v1/tasks/{id}&lt;/a&gt; endpoint to track the progress of this task.
  # @param guid character The unique identifier of the desired content item.
  # @param instructions DeployContentBundleRequest The request body when requesting the deployment of a bundle. (optional)
  # @return [DeployContentBundle202Response]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetContent", {
  # tests for GetContent
  # base path: /__api__
  # Get content details
  # Get detailed information about a specific content item.  Unauthenticated clients are rejected regardless of the content access type.  Authorized, non-administrator clients without viewership rights to this content are rejected.  Authorized, administrator clients without viewership rights are permitted to obtain information about this content. The computed &#x60;role&#x60; for these users will be &#x60;none&#x60;, representing that these users cannot view the content itself.  Authorized clients with viewership (or collaborator) rights are permitted to obtain information about this content. The computed &#x60;role&#x60; for these users will reflect the level of access.  Information about the target environment is populated for users with \&quot;publisher\&quot; and \&quot;administrator\&quot; role; it is suppressed for viewers.
  # @param guid character The unique identifier of the desired content item.
  # @return [Content]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetContentEnvironment", {
  # tests for GetContentEnvironment
  # base path: /__api__
  # Get environment variables
  # Get the names of the environment variables defined for this content.  Since environment variables may contain sensitive information, the values are not included in the returned data.
  # @param guid character The unique identifier of the desired content item.
  # @return [array[character]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetContents", {
  # tests for GetContents
  # base path: /__api__
  # List content items
  # List all content items visible to the requesting user.  Authenticated access from a user is required. If an \&quot;administrator\&quot; role is used, then all content items will be returned regardless of the visibility to the requesting user.  Information about the target environment is populated for users with \&quot;publisher\&quot; and \&quot;administrator\&quot; role; it is suppressed for viewers.
  # @param owner_guid character The unique identifier of the user who owns the content. (optional)
  # @param name character The content name specified when the content was created.  Note: content names are unique within the owning user's account, so a request that specifies a non-empty name and owner_guid will return at most one content item. (optional)
  # @return [array[Content]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("SetContentEnvironment", {
  # tests for SetContentEnvironment
  # base path: /__api__
  # Set all environment variables
  # Set the environment for this content item. Any existing environment variables will be removed, and the ones in the request will be set.
  # @param guid character The unique identifier of the desired content item.
  # @param environment array[EnvironmentVariable] The environment definition to apply to this content item.
  # @return [array[character]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UpdateContent", {
  # tests for UpdateContent
  # base path: /__api__
  # Update content
  # Update fields for a specific content item.  Authenticated access from a user having either \&quot;publisher\&quot; or \&quot;administrator\&quot; role is allowed. All other clients are rejected.  Authorized clients with collaborator or administrator rights are permitted to modify content item fields.  Administrators can reassign content ownership by updating the &#x60;owner_guid&#x60; field. The new owner must have publisher or  administrator rights.
  # @param guid character The unique identifier of the content item to update.
  # @param content UpdateContentRequest The request body required when updating a content item.
  # @return [Content]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UpdateContentEnvironment", {
  # tests for UpdateContentEnvironment
  # base path: /__api__
  # Update environment variables
  # Add, change, or delete environment variables for this content. Variables present in the request body will be set to the values provided. Variables with a value of &#x60;null&#x60; will be deleted. Variables not present in the request body will be left unchanged.
  # @param guid character The unique identifier of the desired content item.
  # @param environment array[EnvironmentVariable] The environment definition to apply to this content item.
  # @return [array[character]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
