# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AuditEntry")

model_instance <- AuditEntry$new()

test_that("id", {
  # tests for the property `id` (character)
  # ID of the audit action

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("time", {
  # tests for the property `time` (character)
  # Timestamp in [RFC3339](https://www.rfc-editor.org/rfc/rfc3339) format when action was taken

  # uncomment below to test the property
  #expect_equal(model.instance$`time`, "EXPECTED_RESULT")
})

test_that("user_id", {
  # tests for the property `user_id` (character)
  # User ID of the actor who made the audit action

  # uncomment below to test the property
  #expect_equal(model.instance$`user_id`, "EXPECTED_RESULT")
})

test_that("user_guid", {
  # tests for the property `user_guid` (character)
  # User GUID of the actor who made the audit action

  # uncomment below to test the property
  #expect_equal(model.instance$`user_guid`, "EXPECTED_RESULT")
})

test_that("user_description", {
  # tests for the property `user_description` (character)
  # Description of the actor

  # uncomment below to test the property
  #expect_equal(model.instance$`user_description`, "EXPECTED_RESULT")
})

test_that("action", {
  # tests for the property `action` (character)
  # Audit action taken

  # uncomment below to test the property
  #expect_equal(model.instance$`action`, "EXPECTED_RESULT")
})

test_that("event_description", {
  # tests for the property `event_description` (character)
  # Description of action

  # uncomment below to test the property
  #expect_equal(model.instance$`event_description`, "EXPECTED_RESULT")
})
