# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DeleteRuntimeCacheResponse")

model_instance <- DeleteRuntimeCacheResponse$new()

test_that("language", {
  # tests for the property `language` (character)
  # The runtime language of the target cache.

  # uncomment below to test the property
  #expect_equal(model.instance$`language`, "EXPECTED_RESULT")
})

test_that("version", {
  # tests for the property `version` (character)
  # The language version of the target cache.

  # uncomment below to test the property
  #expect_equal(model.instance$`version`, "EXPECTED_RESULT")
})

test_that("image_name", {
  # tests for the property `image_name` (character)
  # The name of the target cache&#39;s execution environment.

  # uncomment below to test the property
  #expect_equal(model.instance$`image_name`, "EXPECTED_RESULT")
})

test_that("task_id", {
  # tests for the property `task_id` (character)
  # The identifier for the created deployment task. Always &#x60;null&#x60; for dry-run requests.

  # uncomment below to test the property
  #expect_equal(model.instance$`task_id`, "EXPECTED_RESULT")
})
