# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AuditPagerCursors")

model_instance <- AuditPagerCursors$new()

test_that("previous", {
  # tests for the property `previous` (character)
  # A cursor ID that can be used with the &#x60;previous&#x60; query param to get the previous page of results.

  # uncomment below to test the property
  #expect_equal(model.instance$`previous`, "EXPECTED_RESULT")
})

test_that("next", {
  # tests for the property `next` (character)
  # A cursor ID that can be used with the &#x60;next&#x60; query param to get the next page of results.

  # uncomment below to test the property
  #expect_equal(model.instance$`next`, "EXPECTED_RESULT")
})
