# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test RuntimeCaches")

model_instance <- RuntimeCaches$new()

test_that("caches", {
  # tests for the property `caches` (array[RuntimeCache])

  # uncomment below to test the property
  #expect_equal(model.instance$`caches`, "EXPECTED_RESULT")
})
