# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test TagsApi")

api_instance <- TagsApi$new()

test_that("AddTag", {
  # tests for AddTag
  # base path: /__api__
  # Add tag to content
  # Add the specified tag to an individual content item. When adding a tag, all tags above the specified tag in the tag tree are also added to the content item.  Authenticated access required from an admin or from a user with collaborator/editor permissions on the content item.
  # @param guid character The unique identifier of the content item.
  # @param tag AddTagRequest The request body specifies which tag to add
  # @return [array[Tag]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("CreateTag", {
  # tests for CreateTag
  # base path: /__api__
  # Create tag
  # Create a new tag. Tags without a parent are considered tag \&quot;categories\&quot; and are used to organize other tags. Note that tag categories cannot be added to content items.  Authenticated access from a user having an \&quot;administrator\&quot; role is required.
  # @param tag CreateTagRequest The request body required when creating a new tag.
  # @return [Tag]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeleteTag", {
  # tests for DeleteTag
  # base path: /__api__
  # Delete tag
  # Deletes a tag, including all descendants in its own tag hierarchy.  Authenticated access from a user having an \&quot;administrator\&quot; role is required.
  # @param id character The unique identifier of the tag.
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetTag", {
  # tests for GetTag
  # base path: /__api__
  # Get tag
  # Get an individual tag  Authenticated access from a user is required.
  # @param id character The unique identifier of the tag
  # @return [Tag]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetTagByPath", {
  # tests for GetTagByPath
  # base path: /__api__
  # Get tag by path
  # Get an individual tag by a comma-delimited \&quot;path\&quot; to the tag. The path to the tag is the series of tag names to traverse the tag hierarchy, starting with a tag category.  Authenticated access from a user is required.
  # @param path character The path to the tag, as comma-delimited names
  # @return [Tag]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListContentTags", {
  # tests for ListContentTags
  # base path: /__api__
  # List tags for content
  # List of all tags for the specified content item  Authenticated access required from an admin or from a user with at least viewer permissions on the content item.
  # @param guid character The unique identifier of the content item.
  # @return [array[Tag]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListTagContent", {
  # tests for ListTagContent
  # base path: /__api__
  # List content for tags
  # List all of the content for the specified tag.  Authenticated access from a user is required. If an \&quot;administrator\&quot; role is used, then all content items will be returned regardless of the visibility to the requesting user.  Note that R or Python version information is only provided to clients that authenticate as admin or publisher users; it is suppressed for viewers.
  # @param id character The unique identifier of the tag.
  # @return [array[Content]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListTags", {
  # tests for ListTags
  # base path: /__api__
  # List tags
  # List of all tags.  Authenticated access from a user is required.
  # @param parent_id character The unique identifier of the parent tag (optional)
  # @param name character The tag name  Note: tag names are only unique within the scope of a parent, which means that it is possible to have multiple results when querying by name; however, querying by both `name` and `parent_id` ensures a single result. (optional)
  # @return [array[Tag]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RemoveTag", {
  # tests for RemoveTag
  # base path: /__api__
  # Remove tag from content
  # Remove the specified tag from an individual content item. When removing a tag, all children and descendant tags are also removed from the content item.  Authenticated access required from an admin or from a user with collaborator/editor permissions on the content item.
  # @param guid character The unique identifier of the content item.
  # @param id character The unique identifier of the tag.
  # @return [array[Tag]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UpdateTag", {
  # tests for UpdateTag
  # base path: /__api__
  # Update tag
  # Update an existing tag.  Authenticated access from a user having an \&quot;administrator\&quot; role is required.
  # @param id character The unique identifier of the tag.
  # @param tag UpdateTagRequest The request body required when updating an existing tag.
  # @return [Tag]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
