# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test GroupOwnershipContent")

model_instance <- GroupOwnershipContent$new()

test_that("content_guid", {
  # tests for the property `content_guid` (character)
  # The unique identifier of the content item.

  # uncomment below to test the property
  #expect_equal(model.instance$`content_guid`, "EXPECTED_RESULT")
})

test_that("content_name", {
  # tests for the property `content_name` (character)
  # The name of the content item.

  # uncomment below to test the property
  #expect_equal(model.instance$`content_name`, "EXPECTED_RESULT")
})

test_that("content_title", {
  # tests for the property `content_title` (character)
  # The title of the content item.

  # uncomment below to test the property
  #expect_equal(model.instance$`content_title`, "EXPECTED_RESULT")
})

test_that("access_type", {
  # tests for the property `access_type` (character)
  # The access type of the content item.

  # uncomment below to test the property
  #expect_equal(model.instance$`access_type`, "EXPECTED_RESULT")
})

test_that("permissions", {
  # tests for the property `permissions` (array[GroupOwnershipPermission])
  # List of principals (users and groups) with access to the content. The owner is listed as &#x60;author&#x60; and is always present.

  # uncomment below to test the property
  #expect_equal(model.instance$`permissions`, "EXPECTED_RESULT")
})
