# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BundleV1Exp")

model_instance <- BundleV1Exp$new()

test_that("id", {
  # tests for the property `id` (character)
  # The identifier for this bundle.

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("content_guid", {
  # tests for the property `content_guid` (character)
  # The identifier of the owning content.

  # uncomment below to test the property
  #expect_equal(model.instance$`content_guid`, "EXPECTED_RESULT")
})

test_that("created_time", {
  # tests for the property `created_time` (character)
  # The timestamp (RFC3339) of when this bundle was created.

  # uncomment below to test the property
  #expect_equal(model.instance$`created_time`, "EXPECTED_RESULT")
})

test_that("cluster_name", {
  # tests for the property `cluster_name` (character)
  # The location where this content bundle runs. Content running on the same server as Connect will have either a &#x60;null&#x60; value or the string \&quot;Local\&quot;. Gives the name of the cluster when run external to the Connect host.  Cluster name is not disclosed to users with a \&quot;viewer\&quot; role and returned with the value &#x60;null&#x60;.

  # uncomment below to test the property
  #expect_equal(model.instance$`cluster_name`, "EXPECTED_RESULT")
})

test_that("image_name", {
  # tests for the property `image_name` (character)
  # The location where content this content bundle runs. Content running on the same server as Connect will have either a &#x60;null&#x60; value or the string \&quot;Local\&quot;. References the name of the target image when content runs in a clustered environment such as Kubernetes.  Image name is not disclosed to users with a \&quot;viewer\&quot; role and returned with the value &#x60;null&#x60;.

  # uncomment below to test the property
  #expect_equal(model.instance$`image_name`, "EXPECTED_RESULT")
})

test_that("r_version", {
  # tests for the property `r_version` (character)
  # The version of the R interpreter used when last restoring this bundle. The value &#x60;null&#x60; represents that an R interpreter is not used by this bundle or that the R package environment has not been successfully restored.  R version is not disclosed to users with a \&quot;viewer\&quot; role and returned with the value &#x60;null&#x60;.

  # uncomment below to test the property
  #expect_equal(model.instance$`r_version`, "EXPECTED_RESULT")
})

test_that("py_version", {
  # tests for the property `py_version` (character)
  # The version of the Python interpreter used when last restoring this bundle.  The value &#x60;null&#x60; represents that a Python interpreter is not used by this bundle or that the Python package environment has not been successfully restored.  Python version is not disclosed to users with a \&quot;viewer\&quot; role and returned with the value &#x60;null&#x60;.

  # uncomment below to test the property
  #expect_equal(model.instance$`py_version`, "EXPECTED_RESULT")
})

test_that("quarto_version", {
  # tests for the property `quarto_version` (character)
  # The version of the Quarto interpreter used when last restoring this bundle. The value &#x60;null&#x60; represents that Quarto is not used by this bundle or that the bundle has not been successfully prepared for execution.  Quarto version is not disclosed to users with a \&quot;viewer\&quot; role and returned with the value &#x60;null&#x60;.

  # uncomment below to test the property
  #expect_equal(model.instance$`quarto_version`, "EXPECTED_RESULT")
})

test_that("active", {
  # tests for the property `active` (character)
  # Indicates if this bundle is active for the owning content.

  # uncomment below to test the property
  #expect_equal(model.instance$`active`, "EXPECTED_RESULT")
})

test_that("size", {
  # tests for the property `size` (numeric)
  # On-disk size in bytes of the tar.gz file associated with this bundle. Zero when there is no on-disk file.

  # uncomment below to test the property
  #expect_equal(model.instance$`size`, "EXPECTED_RESULT")
})
