# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UploadContentBundle200Response")

model_instance <- UploadContentBundle200Response$new()

test_that("bundle_id", {
  # tests for the property `bundle_id` (character)
  # Identifier for the newly created bundle.

  # uncomment below to test the property
  #expect_equal(model.instance$`bundle_id`, "EXPECTED_RESULT")
})

test_that("size", {
  # tests for the property `size` (numeric)
  # The number of bytes received.

  # uncomment below to test the property
  #expect_equal(model.instance$`size`, "EXPECTED_RESULT")
})
