# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test GroupsApi")

api_instance <- GroupsApi$new()

test_that("AddGroupMember", {
  # tests for AddGroupMember
  # base path: /__api__
  # Add a group member
  # This endpoint adds a user to a group.  - This endpoint is available only when groups are enabled   in Posit Connect and only for Password, PAM, OAuth2,   SAML and Proxied authentication. If the auth provider   is configured to provide group membership information,   then it is not possible to add/remove members via this API. - Administrator access is required to modify a group you do   not own.
  # @param group_guid character The group's unique identifier
  # @param user AddGroupMemberRequest The user to add as a member
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("CreateGroup", {
  # tests for CreateGroup
  # base path: /__api__
  # Create a group from caller-supplied details (Password, PAM, OAuth2, SAML, Proxied) 
  # This endpoint creates the given group.  - This endpoint is available only when groups are enabled   in Posit Connect and only for Password, PAM, OAuth2,   SAML and Proxied authentication. - Publisher or administrator access is required to create   groups.
  # @param group CreateGroupRequest The new group values.
  # @return [Group]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("CreateRemoteGroup", {
  # tests for CreateRemoteGroup
  # base path: /__api__
  # Create a group using details from a remote authentication provider (LDAP) 
  # This endpoint creates the given group on the Posit Connect server.  - This endpoint is used only for LDAP authentication. Password,   PAM, SAML, OAuth2 and Proxied authentication providers should   use the    &lt;a href&#x3D;\&quot;#post-/v1/groups\&quot;&gt;POST /v1/groups&lt;/a&gt;   endpoint. - Publisher or administrator access is required to access this   endpoint. - Group members will be automatically populated from the LDAP server.  #### Group Creation Workflow on LDAP  The API lets you identify an existing group in the LDAP system and create a corresponding group on Posit Connect. This is a two-step process:  - Use the    &lt;a href&#x3D;\&quot;#get-/v1/groups/remote\&quot;&gt;GET /v1/groups/remote&lt;/a&gt;   endpoint. This endpoint will return a list of potential   matching groups in LDAP. A group that does not exist in   Posit Connect will lack a &#x60;guid&#x60;. Note the &#x60;temp_ticket&#x60;   for the desired group. - Use this PUT endpoint with the &#x60;temp_ticket&#x60; to create a   corresponding group on Posit Connect.  The [Create a Group from LDAP](../cookbook/groups/#create-group-ldap) recipe in the API Cookbook has sample code using this workflow.
  # @param request CreateRemoteGroupRequest The request body needed for creating a group on the Posit Connect server.
  # @return [Group]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeleteGroup", {
  # tests for DeleteGroup
  # base path: /__api__
  # Delete a group
  # Delete the given group.  - This endpoint can be used only when groups are enabled in   Posit Connnect and will return an error otherwise. - Administrator access is required to delete a group you do   not own.
  # @param guid character The group's unique identifier
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetGroup", {
  # tests for GetGroup
  # base path: /__api__
  # Get group details
  # Get detailed information on a specific group.  This endpoint is available only when groups are enabled in Posit Connect.
  # @param guid character The group's unique identifier
  # @return [Group]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetGroupMembers", {
  # tests for GetGroupMembers
  # base path: /__api__
  # Get group member details
  # This endpoint gets the group member details. Group member enumeration is currently not supported for LDAP.  - This endpoint is available only when groups are enabled   in Posit Connect and only for Password, PAM, OAuth2,   SAML and Proxied authentication. - The &#x60;email&#x60; field is not populated for non-admins when   &#x60;Server.HideEmailAddresses&#x60; is enabled.
  # @param group_guid character The group's unique identifier
  # @return [GroupMembers]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetGroupOwnership", {
  # tests for GetGroupOwnership
  # base path: /__api__
  # List content for which a group with given GUID has access to
  # This endpoint takes a group GUID and returns a list of content items with access control lists that the given group is listed on. This includes content accessible only by specific users or groups that include the given group, as well as content accessible by anyone or only logged-in users that includes the given group as a collaborator.
  # @param guid character 
  # @return [array[GroupOwnershipContent]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetGroups", {
  # tests for GetGroups
  # base path: /__api__
  # List or search for group details
  # This endpoint lists or searches for local groups.  - For a &#x60;prefix&#x60; search, results are sorted based on   similarity to the &#x60;prefix&#x60;. A &#x60;prefix&#x60; search ignores   &#x60;asc_order&#x60;. The first page of results will always be   returned. - The &#x60;prefix&#x60; can also be an exact match for the   group&#39;s DN (for LDAP) or the auth provider&#39;s unique ID   for the group, if any. - For a non-&#x60;prefix&#x60; search, results are sorted by group name.  This endpoint is available only when groups are enabled in Posit Connect and it will return an error otherwise.  #### Pagination  This endpoint uses offset pagination (using page numbers). The [Offset Pagination](../cookbook/pagination/#offset-pagination) recipe in the Posit Connect API Cookbook has sample code for fetching multiple pages from a list endpoint.
  # @param prefix character Filters groups by prefix (group name). The filter is case insensitive. (optional)
  # @param page_number integer The page to return relative to the given `page_size`. If `page_number` is 0 or negative, an error will be returned. For a `prefix` search, the first page of results will always be returned. (optional)
  # @param page_size integer The number of items to include in each page. This parameter is \"best effort\" since there may not be enough groups to honor the request. If `page_size` is less than 1 or greater than 500, an error will be returned. (optional)
  # @param asc_order character Whether or not to return the groups in ascending order, sorted by name. For a `prefix` search, results are sorted first by exact match, then by increasing word length. (optional)
  # @return [Groups]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RemoveGroupMember", {
  # tests for RemoveGroupMember
  # base path: /__api__
  # Remove a group member
  # This endpoint removes a user from a group.  - This endpoint is available only when groups are enabled   in Posit Connect and only for Password, PAM, OAuth2,   SAML and Proxied authentication. If the auth provider   is configured to provide group membership information,   then it is not possible to add/remove members via this API. - Administrator access is required to remove a user from a   group you do not own, but no special access is needed to   remove yourself from a group.
  # @param group_guid character The group's unique identifier
  # @param user_guid character The group member's unique identifier
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("SearchRemoteGroups", {
  # tests for SearchRemoteGroups
  # base path: /__api__
  # Search for group details from a remote provider
  # This endpoint is used to support operations against groups not managed by Connect, such as  &lt;a href&#x3D;\&quot;#post-/v1/groups\&quot;&gt;creating LDAP groups&lt;/a&gt; See &lt;a href&#x3D;\&quot;#get-/v1/groups\&quot;&gt;GET /v1/groups&lt;/a&gt; for listing groups on Posit Connect.  This endpoint searches for groups on Posit Connect and on your LDAP system.  Results are sorted based on similarity to the &#x60;prefix&#x60;.  - This endpoint can be used only by LDAP authentication and   will return an error otherwise. - Publisher or administrator access is required to access this   endpoint.
  # @param prefix character Search groups by prefix. `prefix` is case insensitive.
  # @param limit integer The maximum number of groups to include in the results. If `limit` is less than 1 or greater than 500, an error will be returned. (optional)
  # @return [GroupRemoteSearch]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UpdateGroup", {
  # tests for UpdateGroup
  # base path: /__api__
  # Modify a group name or owner (Password, PAM, OAuth2, SAML, Proxied) 
  # This endpoint modifies the given group.  - This endpoint is available only when groups are enabled   in Posit Connect and only for Password, PAM, OAuth2,   SAML and Proxied authentication. - Publisher or administrator access is required to modify   groups.
  # @param guid character The group's unique identifier
  # @param group UpdateGroupRequest The new group name and/or owner.
  # @return [Group]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
