# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test EnvironmentVariable")

model_instance <- EnvironmentVariable$new()

test_that("name", {
  # tests for the property `name` (character)
  # Name of the environment variable.

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("value", {
  # tests for the property `value` (character)
  # New value of the environment variable. A value of &#x60;null&#x60; will delete the environment variable.

  # uncomment below to test the property
  #expect_equal(model.instance$`value`, "EXPECTED_RESULT")
})
