# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test LockUserRequest")

model_instance <- LockUserRequest$new()

test_that("locked", {
  # tests for the property `locked` (character)
  # Whether or not the user should be locked.

  # uncomment below to test the property
  #expect_equal(model.instance$`locked`, "EXPECTED_RESULT")
})
