# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test EditableUser")

model_instance <- EditableUser$new()

test_that("email", {
  # tests for the property `email` (character)
  # The user&#39;s email

  # uncomment below to test the property
  #expect_equal(model.instance$`email`, "EXPECTED_RESULT")
})

test_that("username", {
  # tests for the property `username` (character)
  # The user&#39;s username

  # uncomment below to test the property
  #expect_equal(model.instance$`username`, "EXPECTED_RESULT")
})

test_that("first_name", {
  # tests for the property `first_name` (character)
  # The user&#39;s first name

  # uncomment below to test the property
  #expect_equal(model.instance$`first_name`, "EXPECTED_RESULT")
})

test_that("last_name", {
  # tests for the property `last_name` (character)
  # The user&#39;s last name

  # uncomment below to test the property
  #expect_equal(model.instance$`last_name`, "EXPECTED_RESULT")
})

test_that("user_role", {
  # tests for the property `user_role` (character)
  # The user&#39;s role

  # uncomment below to test the property
  #expect_equal(model.instance$`user_role`, "EXPECTED_RESULT")
})

test_that("updated_time", {
  # tests for the property `updated_time` (character)
  # The timestamp (in [RFC3339](https://www.rfc-editor.org/rfc/rfc3339) format) when the user was last updated in the Posit Connect server

  # uncomment below to test the property
  #expect_equal(model.instance$`updated_time`, "EXPECTED_RESULT")
})
