# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BundlesV1ExperimentalApi")

api_instance <- BundlesV1ExperimentalApi$new()

test_that("DeleteBundle", {
  # tests for DeleteBundle
  # base path: /__api__
  # Delete bundle
  # Delete a specific bundle.  Bundle deletion is permitted by authorized clients with collaborator rights.  On-disk data and database records are removed as a consequence of this call. Deletion is not allowed while the bundle is still active.
  # @param id character The unique identifier of the desired bundle.
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DownloadBundle", {
  # tests for DownloadBundle
  # base path: /__api__
  # Download the bundle archive
  # Download a deployment bundle.  Bundle download is permitted by authorized clients with collaborator rights.  Download a &#x60;gzip&#x60; compressed &#x60;tar&#x60; archive (&#x60;.tar.gz&#x60;) containing the code/data from one deployment of the associated content.  See the  &lt;a href&#x3D;\&quot;#post-/v1/experimental/content/-guid-/upload\&quot;&gt;POST /v1/experimental/content/{guid}/upload&lt;/a&gt; endpoint for details about the construction of bundle archives.
  # @param id character The unique identifier of the desired bundle.
  # @return [data.frame]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetBundle", {
  # tests for GetBundle
  # base path: /__api__
  # Get bundle details
  # Get detailed information about a specific bundle.  Bundle reads are permitted by all users with viewership rights to the content item. Information about the target environment is populated for users with \&quot;publisher\&quot; and \&quot;administrator\&quot; role.
  # @param id character The unique identifier of the desired bundle.
  # @return [BundleV1Exp]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetBundles", {
  # tests for GetBundles
  # base path: /__api__
  # List bundles
  # List bundles associated with a specific content item.  Bundle enumeration is permitted by all users with viewership rights to the content item. Information about the target environment is populated for users with \&quot;publisher\&quot; and \&quot;administrator\&quot; role.  Results are sorted by ID.  #### Pagination  This endpoint uses offset pagination (using page numbers). The [Offset Pagination](../cookbook/pagination/#offset-pagination) recipe in the Posit Connect API Cookbook has sample code for fetching multiple pages from a list endpoint.
  # @param guid character The unique identifier of the desired content item.
  # @param page_number integer The page to return relative to the given `page_size`. If `page_number` is 0 or negative, an error will be returned. (optional)
  # @param page_size integer The number of items to include in each page. This parameter is \"best effort\" since there may not be enough bundles to honor the request. If `page_size` is less than 1 or greater than 500, an error will be returned. (optional)
  # @return [BundlesV1Exp]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
