# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CreateRemoteGroupRequest")

model_instance <- CreateRemoteGroupRequest$new()

test_that("temp_ticket", {
  # tests for the property `temp_ticket` (character)
  # The temporary ticket used for creating a group on the Posit Connect server. It is obtained from the &lt;a href&#x3D;\&quot;#get-/v1/groups/remote\&quot;&gt;GET /v1/groups/remote&lt;/a&gt; endpoint.

  # uncomment below to test the property
  #expect_equal(model.instance$`temp_ticket`, "EXPECTED_RESULT")
})
