# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Bundle")

model_instance <- Bundle$new()

test_that("id", {
  # tests for the property `id` (character)
  # The identifier for this bundle.

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("content_guid", {
  # tests for the property `content_guid` (character)
  # The identifier of the owning content.

  # uncomment below to test the property
  #expect_equal(model.instance$`content_guid`, "EXPECTED_RESULT")
})

test_that("created_time", {
  # tests for the property `created_time` (character)
  # The timestamp (RFC3339) of when this bundle was created.

  # uncomment below to test the property
  #expect_equal(model.instance$`created_time`, "EXPECTED_RESULT")
})

test_that("cluster_name", {
  # tests for the property `cluster_name` (character)
  # The location where this content runs. Content running on the same server as Connect will have either a &#x60;null&#x60; value or the string \&quot;Local\&quot;. Gives the name of the cluster when run external to the Connect host.  Cluster name is not disclosed to users with a \&quot;viewer\&quot; role and returned with the value &#x60;null&#x60;.

  # uncomment below to test the property
  #expect_equal(model.instance$`cluster_name`, "EXPECTED_RESULT")
})

test_that("image_name", {
  # tests for the property `image_name` (character)
  # The location where content this content runs. Content running on the same server as Connect will have either a &#x60;null&#x60; value or the string \&quot;Local\&quot;. References the name of the target image when content runs in a clustered environment such as Kubernetes.  Image name is not disclosed to users with a \&quot;viewer\&quot; role and returned with the value &#x60;null&#x60;.

  # uncomment below to test the property
  #expect_equal(model.instance$`image_name`, "EXPECTED_RESULT")
})

test_that("r_version", {
  # tests for the property `r_version` (character)
  # The version of R used when last restoring this bundle. A &#x60;null&#x60; value represents that R is not used by this bundle or that the bundle has not been prepared for execution.  R version is not disclosed to users with a \&quot;viewer\&quot; role; they receive a &#x60;null&#x60; value.

  # uncomment below to test the property
  #expect_equal(model.instance$`r_version`, "EXPECTED_RESULT")
})

test_that("r_environment_management", {
  # tests for the property `r_environment_management` (character)
  # Indicates whether or not Connect is managing an R environment and has installed the required packages for this content. The &#x60;null&#x60; value represents that R is not used by this bundle or that it has not yet been determined if an R environment is required.  R environment management is not disclosed to users with a \&quot;viewer\&quot; role; they receive a &#x60;null&#x60; value.

  # uncomment below to test the property
  #expect_equal(model.instance$`r_environment_management`, "EXPECTED_RESULT")
})

test_that("py_version", {
  # tests for the property `py_version` (character)
  # The version of Python used when last restoring this bundle. A &#x60;null&#x60; value represents that Python is not used by this bundle or that the bundle has not been prepared for execution.  Python version is not disclosed to users with a \&quot;viewer\&quot; role; they receive a &#x60;null&#x60; value.

  # uncomment below to test the property
  #expect_equal(model.instance$`py_version`, "EXPECTED_RESULT")
})

test_that("py_environment_management", {
  # tests for the property `py_environment_management` (character)
  # Indicates whether or not Connect is managing a Python environment and has installed the required packages for this content. The &#x60;null&#x60; value represents that Python is not used by this bundle or that it has not yet been determined if a Python environment is required.  Python environment management is not disclosed to users with a \&quot;viewer\&quot; role; they receive a &#x60;null&#x60; value.

  # uncomment below to test the property
  #expect_equal(model.instance$`py_environment_management`, "EXPECTED_RESULT")
})

test_that("quarto_version", {
  # tests for the property `quarto_version` (character)
  # The version of Quarto used when last restoring this bundle. A &#x60;null&#x60; value represents that Quarto is not used by this bundle or that the bundle has not been successfully prepared for execution.  Quarto version is not disclosed to users with a \&quot;viewer\&quot; role; they receive a &#x60;null&#x60; value.

  # uncomment below to test the property
  #expect_equal(model.instance$`quarto_version`, "EXPECTED_RESULT")
})

test_that("active", {
  # tests for the property `active` (character)
  # Indicates if this bundle is active for the owning content.

  # uncomment below to test the property
  #expect_equal(model.instance$`active`, "EXPECTED_RESULT")
})

test_that("size", {
  # tests for the property `size` (integer)
  # On-disk size in bytes of the tar.gz file associated with this bundle. Zero when there is no on-disk file.

  # uncomment below to test the property
  #expect_equal(model.instance$`size`, "EXPECTED_RESULT")
})

test_that("metadata", {
  # tests for the property `metadata` (BundleMetadata)

  # uncomment below to test the property
  #expect_equal(model.instance$`metadata`, "EXPECTED_RESULT")
})
