# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test RInformationApi")

api_instance <- RInformationApi$new()

test_that("GetRInformation", {
  # tests for GetRInformation
  # base path: /__api__
  # Get R Information
  # This endpoint returns a list of metadata objects for each version of R that is available for executing content.  This endpoint requires authentication and is only available to &#x60;publisher&#x60; and &#x60;administrator&#x60; roles.  The [R Versions Available](../cookbook/system-information/#available-r-versions) recipe in the Posit Connect API Cookbook contains a recipe with sample code.
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
