# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ContentPermissionsApi")

api_instance <- ContentPermissionsApi$new()

test_that("AddContentPermission", {
  # tests for AddContentPermission
  # base path: /__api__
  # Add permission
  # Add a user or group to the permissions for this content item.
  # @param guid character The unique identifier of the desired content item.
  # @param permission AddContentPermissionRequest The request body required when creating a new permission entry.
  # @return [Permission]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeleteContentPermission", {
  # tests for DeleteContentPermission
  # base path: /__api__
  # Delete permission
  # Delete a single permission entry for the content item, given its ID.
  # @param guid character The unique identifier of the desired content item.
  # @param id character The unique identifier of the permission entry.
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetContentPermission", {
  # tests for GetContentPermission
  # base path: /__api__
  # Get permission
  # Get a single permission entry for the content item, given its ID.
  # @param guid character The unique identifier of the desired content item.
  # @param id character The unique identifier of the permission entry.
  # @return [Permission]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListContentPermissions", {
  # tests for ListContentPermissions
  # base path: /__api__
  # List permissions
  # List the permissions for this content item. There will be one permission item for each user or group listed in the ACL for this content item.
  # @param guid character The unique identifier of the desired content item.
  # @return [array[Permission]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UpdateContentPermission", {
  # tests for UpdateContentPermission
  # base path: /__api__
  # Update permission
  # Update a permission entry for this content item.
  # @param guid character The unique identifier of the desired content item.
  # @param id character The unique identifier of the permission entry to update.
  # @param permission UpdateContentPermissionRequest The request body required when creating a new permission entry.
  # @return [Permission]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
