# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test LogEntries")

model_instance <- LogEntries$new()

test_that("entries", {
  # tests for the property `entries` (array[LogEntry])

  # uncomment below to test the property
  #expect_equal(model.instance$`entries`, "EXPECTED_RESULT")
})
