# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SetVanity200Response")

model_instance <- SetVanity200Response$new()

test_that("path", {
  # tests for the property `path` (character)
  # The URL path that will be used by this application. HTTP requests to this path on the Connect server will be routed to the associated content item.

  # uncomment below to test the property
  #expect_equal(model.instance$`path`, "EXPECTED_RESULT")
})

test_that("content_guid", {
  # tests for the property `content_guid` (character)
  # The unique identifier of the associated content item.

  # uncomment below to test the property
  #expect_equal(model.instance$`content_guid`, "EXPECTED_RESULT")
})

test_that("created_time", {
  # tests for the property `created_time` (character)
  # The timestamp (RFC3339) indicating when this vanity URL was created.

  # uncomment below to test the property
  #expect_equal(model.instance$`created_time`, "EXPECTED_RESULT")
})
