# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AddTagRequest")

model_instance <- AddTagRequest$new()

test_that("tag_id", {
  # tests for the property `tag_id` (character)
  # The unique identifier for the tag

  # uncomment below to test the property
  #expect_equal(model.instance$`tag_id`, "EXPECTED_RESULT")
})
