# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CreateEnvironmentInputPython")

model_instance <- CreateEnvironmentInputPython$new()

test_that("installations", {
  # tests for the property `installations` (array[Installation])

  # uncomment below to test the property
  #expect_equal(model.instance$`installations`, "EXPECTED_RESULT")
})
