# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UserWithTicket")

model_instance <- UserWithTicket$new()

test_that("guid", {
  # tests for the property `guid` (character)
  # The user&#39;s GUID, or unique identifier in [RFC4122](https://www.rfc-editor.org/rfc/rfc4122) format. When a user does not exist in the Posit Connect server, this property will be &#x60;null&#x60;.

  # uncomment below to test the property
  #expect_equal(model.instance$`guid`, "EXPECTED_RESULT")
})

test_that("email", {
  # tests for the property `email` (character)
  # The user&#39;s email

  # uncomment below to test the property
  #expect_equal(model.instance$`email`, "EXPECTED_RESULT")
})

test_that("username", {
  # tests for the property `username` (character)
  # The user&#39;s username

  # uncomment below to test the property
  #expect_equal(model.instance$`username`, "EXPECTED_RESULT")
})

test_that("first_name", {
  # tests for the property `first_name` (character)
  # The user&#39;s first name

  # uncomment below to test the property
  #expect_equal(model.instance$`first_name`, "EXPECTED_RESULT")
})

test_that("last_name", {
  # tests for the property `last_name` (character)
  # The user&#39;s last name

  # uncomment below to test the property
  #expect_equal(model.instance$`last_name`, "EXPECTED_RESULT")
})

test_that("user_role", {
  # tests for the property `user_role` (character)
  # The user&#39;s role

  # uncomment below to test the property
  #expect_equal(model.instance$`user_role`, "EXPECTED_RESULT")
})

test_that("created_time", {
  # tests for the property `created_time` (character)
  # The timestamp (in [RFC3339](https://www.rfc-editor.org/rfc/rfc3339) format) when the user was created in the Posit Connect server

  # uncomment below to test the property
  #expect_equal(model.instance$`created_time`, "EXPECTED_RESULT")
})

test_that("updated_time", {
  # tests for the property `updated_time` (character)
  # The timestamp (in [RFC3339](https://www.rfc-editor.org/rfc/rfc3339) format) when the user was last updated in the Posit Connect server

  # uncomment below to test the property
  #expect_equal(model.instance$`updated_time`, "EXPECTED_RESULT")
})

test_that("active_time", {
  # tests for the property `active_time` (character)
  # The timestamp (in [RFC3339](https://www.rfc-editor.org/rfc/rfc3339) format) when the user was last active on the Posit Connect server

  # uncomment below to test the property
  #expect_equal(model.instance$`active_time`, "EXPECTED_RESULT")
})

test_that("confirmed", {
  # tests for the property `confirmed` (character)
  # Whether or not the user is confirmed. This property will always be &#x60;true&#x60; for all authentication providers except password.

  # uncomment below to test the property
  #expect_equal(model.instance$`confirmed`, "EXPECTED_RESULT")
})

test_that("locked", {
  # tests for the property `locked` (character)
  # Whether or not the user is locked

  # uncomment below to test the property
  #expect_equal(model.instance$`locked`, "EXPECTED_RESULT")
})

test_that("temp_ticket", {
  # tests for the property `temp_ticket` (character)
  # This value is for actions that require a &#x60;temp_ticket&#x60;, such as adding an LDAP or OAuth2 with Google user to the Connect server.

  # uncomment below to test the property
  #expect_equal(model.instance$`temp_ticket`, "EXPECTED_RESULT")
})
