# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test GroupMembers")

model_instance <- GroupMembers$new()

test_that("current_page", {
  # tests for the property `current_page` (integer)
  # The current page of results

  # uncomment below to test the property
  #expect_equal(model.instance$`current_page`, "EXPECTED_RESULT")
})

test_that("total", {
  # tests for the property `total` (integer)
  # The number of group members

  # uncomment below to test the property
  #expect_equal(model.instance$`total`, "EXPECTED_RESULT")
})

test_that("results", {
  # tests for the property `results` (array[User])
  # The group members list

  # uncomment below to test the property
  #expect_equal(model.instance$`results`, "EXPECTED_RESULT")
})
