# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PythonInformationApi")

api_instance <- PythonInformationApi$new()

test_that("GetPythonInformation", {
  # tests for GetPythonInformation
  # base path: /__api__
  # Get Python Information
  # This endpoint returns a list of metadata objects for each version of Python that is available for executing content.  This endpoint requires authentication and is only available to &#x60;publisher&#x60; and &#x60;administrator&#x60; roles.
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
