# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test GetTask200Response")

model_instance <- GetTask200Response$new()

test_that("id", {
  # tests for the property `id` (character)
  # The identifier for this task.

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("output", {
  # tests for the property `output` (array[character])
  # An array containing lines of output produced by the task. The initial line of output is dictated by the &#x60;first&#x60; input parameter. The offset of the last output line is indicated by the &#x60;last&#x60; response field.

  # uncomment below to test the property
  #expect_equal(model.instance$`output`, "EXPECTED_RESULT")
})

test_that("finished", {
  # tests for the property `finished` (character)
  # Indicates that a task has completed.

  # uncomment below to test the property
  #expect_equal(model.instance$`finished`, "EXPECTED_RESULT")
})

test_that("code", {
  # tests for the property `code` (integer)
  # Numeric indication as to the cause of an error. Non-zero when an error has occured.

  # uncomment below to test the property
  #expect_equal(model.instance$`code`, "EXPECTED_RESULT")
})

test_that("error", {
  # tests for the property `error` (character)
  # Description of the error. An empty string when no error has occurred.

  # uncomment below to test the property
  #expect_equal(model.instance$`error`, "EXPECTED_RESULT")
})

test_that("last", {
  # tests for the property `last` (integer)
  # The total number of output lines produced so far. Use as the value to &#x60;first&#x60; in the next request to only fetch output lines beyond what you have already received.

  # uncomment below to test the property
  #expect_equal(model.instance$`last`, "EXPECTED_RESULT")
})
