# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UpdateContentRequest1")

model_instance <- UpdateContentRequest1$new()

test_that("name", {
  # tests for the property `name` (character)
  # A simple, URL-friendly identifier. Allows alpha-numeric characters, hyphens (&#x60;\&quot;-\&quot;&#x60;), and underscores (&#x60;\&quot;_\&quot;&#x60;).

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("title", {
  # tests for the property `title` (character)
  # The title of this content.

  # uncomment below to test the property
  #expect_equal(model.instance$`title`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)
  # A rich description of this content.

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("access_type", {
  # tests for the property `access_type` (character)
  # Access type describes how this content manages its viewers. The value &#x60;all&#x60; is the most permissive; any visitor to Posit Connect will be able to view this content. The value &#x60;logged_in&#x60; indicates that all Posit Connect accounts may view the content. The &#x60;acl&#x60; value lets specifically enumerated users and groups view the content. Users configured as collaborators may always view content.

  # uncomment below to test the property
  #expect_equal(model.instance$`access_type`, "EXPECTED_RESULT")
})

test_that("connection_timeout", {
  # tests for the property `connection_timeout` (integer)
  # Maximum number of seconds allowed without data sent or received across a client connection. A value of &#x60;0&#x60; means connections will never time-out (not recommended). When &#x60;null&#x60;, the default &#x60;Scheduler.ConnectionTimeout&#x60; is used. Applies only to content types that are executed on demand.

  # uncomment below to test the property
  #expect_equal(model.instance$`connection_timeout`, "EXPECTED_RESULT")
})

test_that("read_timeout", {
  # tests for the property `read_timeout` (integer)
  # Maximum number of seconds allowed without data received from a client connection. A value of &#x60;0&#x60; means a lack of client (browser) interaction never causes the connection to close. When &#x60;null&#x60;, the default &#x60;Scheduler.ReadTimeout&#x60; is used. Applies only to content types that are executed on demand.

  # uncomment below to test the property
  #expect_equal(model.instance$`read_timeout`, "EXPECTED_RESULT")
})

test_that("init_timeout", {
  # tests for the property `init_timeout` (integer)
  # The maximum number of seconds allowed for an interactive application to start. Posit Connect must be able to connect to a newly launched Shiny application, for example, before this threshold has elapsed. When &#x60;null&#x60;, the default &#x60;Scheduler.InitTimeout&#x60; is used. Applies only to content types that are executed on demand.

  # uncomment below to test the property
  #expect_equal(model.instance$`init_timeout`, "EXPECTED_RESULT")
})

test_that("idle_timeout", {
  # tests for the property `idle_timeout` (integer)
  # The maximum number of seconds a worker process for an interactive application to remain alive after it goes idle (no active connections). When &#x60;null&#x60;, the default &#x60;Scheduler.IdleTimeout&#x60; is used. Applies only to content types that are executed on demand.

  # uncomment below to test the property
  #expect_equal(model.instance$`idle_timeout`, "EXPECTED_RESULT")
})

test_that("max_processes", {
  # tests for the property `max_processes` (integer)
  # Specifies the total number of concurrent processes allowed for a single interactive application. When &#x60;null&#x60;, the default &#x60;Scheduler.MaxProcesses&#x60; is used. Applies only to content types that are executed on demand.

  # uncomment below to test the property
  #expect_equal(model.instance$`max_processes`, "EXPECTED_RESULT")
})

test_that("min_processes", {
  # tests for the property `min_processes` (integer)
  # Specifies the minimum number of concurrent processes allowed for a single interactive application. When &#x60;null&#x60;, the default &#x60;Scheduler.MinProcesses&#x60; is used. Applies only to content types that are executed on demand.

  # uncomment below to test the property
  #expect_equal(model.instance$`min_processes`, "EXPECTED_RESULT")
})

test_that("max_conns_per_process", {
  # tests for the property `max_conns_per_process` (integer)
  # Specifies the maximum number of client connections allowed to an individual process. Incoming connections which will exceed this limit are routed to a new process or rejected. When &#x60;null&#x60;, the default &#x60;Scheduler.MaxConnsPerProcess&#x60; is used. Applies only to content types that are executed on demand.

  # uncomment below to test the property
  #expect_equal(model.instance$`max_conns_per_process`, "EXPECTED_RESULT")
})

test_that("load_factor", {
  # tests for the property `load_factor` (numeric)
  # Controls how aggressively new processes are spawned. When &#x60;null&#x60;, the default &#x60;Scheduler.LoadFactor&#x60; is used. Applies only to content types that are executed on demand.

  # uncomment below to test the property
  #expect_equal(model.instance$`load_factor`, "EXPECTED_RESULT")
})
