# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DeleteRuntimeCacheRequest")

model_instance <- DeleteRuntimeCacheRequest$new()

test_that("language", {
  # tests for the property `language` (character)
  # The language of the target cache; either \&quot;R\&quot; or \&quot;Python\&quot;.

  # uncomment below to test the property
  #expect_equal(model.instance$`language`, "EXPECTED_RESULT")
})

test_that("version", {
  # tests for the property `version` (character)
  # The version of the target cache.

  # uncomment below to test the property
  #expect_equal(model.instance$`version`, "EXPECTED_RESULT")
})

test_that("image_name", {
  # tests for the property `image_name` (character)
  # The execution environment of the target cache; either \&quot;Local\&quot; or an image name or identifier.

  # uncomment below to test the property
  #expect_equal(model.instance$`image_name`, "EXPECTED_RESULT")
})

test_that("dry_run", {
  # tests for the property `dry_run` (character)
  # When true, check input but do not delete cache.

  # uncomment below to test the property
  #expect_equal(model.instance$`dry_run`, "EXPECTED_RESULT")
})
