# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test JobsApi")

api_instance <- JobsApi$new()

test_that("GetJob", {
  # tests for GetJob
  # base path: /__api__
  # Get job
  # Get a job for a given piece of content by key. This action is permitted for content owners, users with collaborator rights, and administrators.
  # @param guid character The unique identifier of the desired content item
  # @param key character The job's unique key
  # @return [JobItem]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetJobs", {
  # tests for GetJobs
  # base path: /__api__
  # Get jobs
  # Get the list of jobs for a given piece of content. This action is permitted for content owners, users with collaborator rights, and administrators.
  # @param guid character The unique identifier of the desired content item
  # @return [array[JobItem]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("JobDownloadLog", {
  # tests for JobDownloadLog
  # base path: /__api__
  # Download job log file
  # Download a content job log file. This action is permitted for content owners, users with collaborator rights, and administrators.
  # @param guid character The unique identifier of the desired content item
  # @param key character The job's unique key
  # @param filename character The name of the file to retrieve (optional)
  # @return [data.frame]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("JobError", {
  # tests for JobError
  # base path: /__api__
  # Get job error
  # Get the primary error for a job (if one exists). This action is permitted for content owners, users with collaborator rights, and administrators.
  # @param guid character The unique identifier of the desired content item
  # @param key character The job's unique key
  # @return [LoggedError]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("JobLogs", {
  # tests for JobLogs
  # base path: /__api__
  # Get job log
  # Get the log output for a given job. This action is permitted for content owners, users with collaborator rights, and administrators.
  # @param guid character The unique identifier of the desired content item
  # @param key character The job's unique key
  # @param max_log_lines integer The maximum number of log lines to return (optional)
  # @return [LogEntries]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("JobTailLog", {
  # tests for JobTailLog
  # base path: /__api__
  # Tail job log
  # Actively tail the log output for a given job. This action is permitted for content owners, users with collaborator rights, and administrators.
  # @param guid character The unique identifier of the desired content item
  # @param key character The job's unique key
  # @return [LogEntry]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("KillJob", {
  # tests for KillJob
  # base path: /__api__
  # Register job kill order
  # Request to register an order to kill a specific job.  This action is permitted for content owners, users with collaborator rights, and administrators.
  # @param guid character The unique identifier of the desired content item
  # @param key character The job's unique key
  # @return [KillJobOrder]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
