# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SetVanityRequest")

model_instance <- SetVanityRequest$new()

test_that("path", {
  # tests for the property `path` (character)
  # The URL path that will be assigned to this content item. HTTP requests to this path on the Connect server will be routed to the associated content item.

  # uncomment below to test the property
  #expect_equal(model.instance$`path`, "EXPECTED_RESULT")
})

test_that("force", {
  # tests for the property `force` (character)
  # If true, and a vanity URL exists with the specified path, reassign it to the specified content item. To reassign a vanity URL, you must be an administrator, or a collaborator/owner of both content items.

  # uncomment below to test the property
  #expect_equal(model.instance$`force`, "EXPECTED_RESULT")
})
