# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DeployContentBundleRequest1")

model_instance <- DeployContentBundleRequest1$new()

test_that("bundle_id", {
  # tests for the property `bundle_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`bundle_id`, "EXPECTED_RESULT")
})
