# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BootstrapSuccess")

model_instance <- BootstrapSuccess$new()

test_that("api_key", {
  # tests for the property `api_key` (character)
  # The API key for the newly created administrator user.

  # uncomment below to test the property
  #expect_equal(model.instance$`api_key`, "EXPECTED_RESULT")
})
