# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test GroupWithTicket")

model_instance <- GroupWithTicket$new()

test_that("guid", {
  # tests for the property `guid` (character)
  # The group&#39;s unique identifier in [RFC4122](https://tools.ietf.org/html/rfc4122) format. When a group does not exist in the Posit Connect server, this property will be &#x60;null&#x60;.

  # uncomment below to test the property
  #expect_equal(model.instance$`guid`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # The group name

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("temp_ticket", {
  # tests for the property `temp_ticket` (character)
  # This value is for actions that require a &#x60;temp_ticket&#x60;, such as adding an LDAP group to the Connect server.

  # uncomment below to test the property
  #expect_equal(model.instance$`temp_ticket`, "EXPECTED_RESULT")
})
