# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DeployContentBundle202Response")

model_instance <- DeployContentBundle202Response$new()

test_that("task_id", {
  # tests for the property `task_id` (character)
  # Identifier for the created deployment task.

  # uncomment below to test the property
  #expect_equal(model.instance$`task_id`, "EXPECTED_RESULT")
})
