# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UpdateGroupRequest")

model_instance <- UpdateGroupRequest$new()

test_that("name", {
  # tests for the property `name` (character)
  # The group&#39;s desired name

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("owner_guid", {
  # tests for the property `owner_guid` (character)
  # The group owner&#39;s unique identifier. When using SAML/OAuth2/Proxied authentication with group provisioning enabled this property must always be &#x60;null&#x60;. Any existing owner is also removed in this condition.

  # uncomment below to test the property
  #expect_equal(model.instance$`owner_guid`, "EXPECTED_RESULT")
})
