# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test RuntimeCachesApi")

api_instance <- RuntimeCachesApi$new()

test_that("DeleteRuntimeCache", {
  # tests for DeleteRuntimeCache
  # base path: /__api__
  # Delete a runtime cache
  # Delete a content runtime package cache by specifying language, version, and execution environment. This action is only available to administrators.
  # @param cache DeleteRuntimeCacheRequest The target runtime cache.
  # @return [DeleteRuntimeCacheResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListRuntimeCaches", {
  # tests for ListRuntimeCaches
  # base path: /__api__
  # List runtime caches
  # List all content runtime caches. These include packrat and Python environment caches. This information is available only to administrators.
  # @return [RuntimeCaches]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
