# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test LoggedError")

model_instance <- LoggedError$new()

test_that("code", {
  # tests for the property `code` (character)
  # The error code.

  # uncomment below to test the property
  #expect_equal(model.instance$`code`, "EXPECTED_RESULT")
})

test_that("summary", {
  # tests for the property `summary` (character)
  # Summary of the error.

  # uncomment below to test the property
  #expect_equal(model.instance$`summary`, "EXPECTED_RESULT")
})

test_that("help_url", {
  # tests for the property `help_url` (character)
  # A help URL with further information about the error.

  # uncomment below to test the property
  #expect_equal(model.instance$`help_url`, "EXPECTED_RESULT")
})
