# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AddGroupMemberRequest")

model_instance <- AddGroupMemberRequest$new()

test_that("user_guid", {
  # tests for the property `user_guid` (character)
  # The user&#39;s unique identifier

  # uncomment below to test the property
  #expect_equal(model.instance$`user_guid`, "EXPECTED_RESULT")
})
