# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Group")

model_instance <- Group$new()

test_that("guid", {
  # tests for the property `guid` (character)
  # The unique identifier

  # uncomment below to test the property
  #expect_equal(model.instance$`guid`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # The group name

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("owner_guid", {
  # tests for the property `owner_guid` (character)
  # The group owner&#39;s unique identifier. When using LDAP, or SAML/OAuth2/Proxied authentication with group provisioning enabled this property will always be &#x60;null&#x60;.

  # uncomment below to test the property
  #expect_equal(model.instance$`owner_guid`, "EXPECTED_RESULT")
})
