# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test QuartoInformationApi")

api_instance <- QuartoInformationApi$new()

test_that("GetQuartoInformation", {
  # tests for GetQuartoInformation
  # base path: /__api__
  # Get Quarto Information
  # This endpoint returns a list of metadata objects for each version of Quarto that is available for executing content.  This endpoint requires authentication and is only available to &#x60;publisher&#x60; and &#x60;administrator&#x60; roles.
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
