# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CreatePushUserRequest")

model_instance <- CreatePushUserRequest$new()

test_that("username", {
  # tests for the property `username` (character)
  # The user&#39;s desired username

  # uncomment below to test the property
  #expect_equal(model.instance$`username`, "EXPECTED_RESULT")
})

test_that("email", {
  # tests for the property `email` (character)
  # The user&#39;s email.

  # uncomment below to test the property
  #expect_equal(model.instance$`email`, "EXPECTED_RESULT")
})

test_that("first_name", {
  # tests for the property `first_name` (character)
  # The user&#39;s first name

  # uncomment below to test the property
  #expect_equal(model.instance$`first_name`, "EXPECTED_RESULT")
})

test_that("last_name", {
  # tests for the property `last_name` (character)
  # The user&#39;s last name

  # uncomment below to test the property
  #expect_equal(model.instance$`last_name`, "EXPECTED_RESULT")
})

test_that("user_role", {
  # tests for the property `user_role` (character)
  # The user&#39;s role. If &#x60;null&#x60; it will default to the role specified by the config setting &#x60;Authorization.DefaultUserRole&#x60;.

  # uncomment below to test the property
  #expect_equal(model.instance$`user_role`, "EXPECTED_RESULT")
})

test_that("user_must_set_password", {
  # tests for the property `user_must_set_password` (character)
  # Applies only to password authentication.  - When &#x60;true&#x60;, the created user will be asked to set their password on first login. The &#x60;password&#x60; request parameter cannot be set when this parameter is &#x60;true&#x60;. - When &#x60;false&#x60;, you must specify the &#x60;password&#x60;.

  # uncomment below to test the property
  #expect_equal(model.instance$`user_must_set_password`, "EXPECTED_RESULT")
})

test_that("password", {
  # tests for the property `password` (character)
  # Applies only to password authentication. Must be at least 6 characters long. Cannot be set when &#x60;user_must_set_password&#x60; is true.

  # uncomment below to test the property
  #expect_equal(model.instance$`password`, "EXPECTED_RESULT")
})

test_that("unique_id", {
  # tests for the property `unique_id` (character)
  # Applies only to proxied authentication when &#x60;ProxyAuth.UniqueIdHeader&#x60; is being used.  It is required when SAML or OAuth2 (non-Google) authentication is being used.

  # uncomment below to test the property
  #expect_equal(model.instance$`unique_id`, "EXPECTED_RESULT")
})
