# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test KillJobOrder")

model_instance <- KillJobOrder$new()

test_that("guid", {
  # tests for the property `guid` (character)
  # The unique identifier for the registered kill order.

  # uncomment below to test the property
  #expect_equal(model.instance$`guid`, "EXPECTED_RESULT")
})

test_that("app_id", {
  # tests for the property `app_id` (integer)
  # The identifier for this job&#39;s parent content.

  # uncomment below to test the property
  #expect_equal(model.instance$`app_id`, "EXPECTED_RESULT")
})

test_that("app_guid", {
  # tests for the property `app_guid` (character)
  # The unique identifier for this job&#39;s content.

  # uncomment below to test the property
  #expect_equal(model.instance$`app_guid`, "EXPECTED_RESULT")
})

test_that("job_id", {
  # tests for the property `job_id` (integer)
  # The job&#39;s id

  # uncomment below to test the property
  #expect_equal(model.instance$`job_id`, "EXPECTED_RESULT")
})

test_that("job_key", {
  # tests for the property `job_key` (character)
  # The job&#39;s unique key identifier.

  # uncomment below to test the property
  #expect_equal(model.instance$`job_key`, "EXPECTED_RESULT")
})

test_that("result", {
  # tests for the property `result` (character)
  # A short message describing the end result.

  # uncomment below to test the property
  #expect_equal(model.instance$`result`, "EXPECTED_RESULT")
})
