# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Tag")

model_instance <- Tag$new()

test_that("id", {
  # tests for the property `id` (character)
  # The identifier for the tag.

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # The name of the tag.

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("parent_id", {
  # tests for the property `parent_id` (character)
  # The identifier for the parent tag. If there is no parent_id, the tag is a top-level tag.

  # uncomment below to test the property
  #expect_equal(model.instance$`parent_id`, "EXPECTED_RESULT")
})

test_that("created_time", {
  # tests for the property `created_time` (character)
  # The timestamp (RFC3339) indicating when the tag was created.

  # uncomment below to test the property
  #expect_equal(model.instance$`created_time`, "EXPECTED_RESULT")
})

test_that("updated_time", {
  # tests for the property `updated_time` (character)
  # The timestamp (RFC3339) indicating when the tag was created.

  # uncomment below to test the property
  #expect_equal(model.instance$`updated_time`, "EXPECTED_RESULT")
})
