# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UsersApi")

api_instance <- UsersApi$new()

test_that("CreatePullUser", {
  # tests for CreatePullUser
  # base path: /__api__
  # Create a user using details from a remote authentication provider (LDAP, OAuth2 with Google) 
  # This endpoint creates the given user on the Posit Connect server.  - This endpoint is used only for LDAP and OAuth2 with Google   authentication. All other authentication providers should   use the    &lt;a href&#x3D;\&quot;#post-/v1/users\&quot;&gt;POST /v1/users&lt;/a&gt;   endpoint. - Unlike the   &lt;a href&#x3D;\&quot;#post-/v1/users\&quot;&gt;POST /v1/users&lt;/a&gt;   endpoint, publisher or administrator access is required to access this   endpoint.  #### User Creation Workflow on LDAP and OAuth2 with Google  This endpoint requires authentication, which means that you need an API Key for access. How do you get an API Key if there are no users in Posit Connect? The first user can be created by simply logging into Posit Connect. The Posit Connect Server API cannot be used to create the first user. Once logged in, you can create an API Key.  For LDAP and OAuth2 with Google, the API lets you identify an existing user in the LDAP or OAuth2 with Google system and create a corresponding account on Posit Connect. This is a two-step process:  - Use the    &lt;a href&#x3D;\&quot;#get-/v1/users/remote\&quot;&gt;GET /v1/users/remote&lt;/a&gt;   endpoint. This   endpoint will return a list of potential matching accounts   in LDAP or OAuth2 with Google. A user with no account on Posit Connect will   lack a &#x60;guid&#x60;. Note the &#x60;temp_ticket&#x60; for the desired user   account. - Use this PUT endpoint with the &#x60;temp_ticket&#x60; to create a   corresponding account on Posit Connect.  The [Create a User from LDAP/OAuth](../cookbook/users/#create-user-ldap-oauth2) recipe in the API Cookbook has sample code using this workflow.  #### LDAP and OAuth2 with Google Authentication  - The created user role will default to the role specified by   the config setting &#x60;Authorization.DefaultUserRole&#x60;.
  # @param request CreatePullUserRequest The request body needed for creating a user on the Posit Connect server.
  # @return [User]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("CreatePushUser", {
  # tests for CreatePushUser
  # base path: /__api__
  # Create a user from caller-supplied details (SAML, password, PAM, proxied, OAuth2 except with Google) 
  # This endpoint creates the given user.  - This endpoint is used only for SAML, OAuth2 (non-Google), password, PAM, and proxied   authentication. All other authentication providers should   use the    &lt;a href&#x3D;\&quot;#put-/v1/users\&quot;&gt;PUT /v1/users&lt;/a&gt;   endpoint. - Administrator access is required to create *other* users.  #### Initial User Creation Workflow  This endpoint requires authentication to create *other* users, which means that you need an API Key for access. How do you get an API Key if there are no users in Posit Connect?  - For password authentication, you can use this endpoint   without an API Key to create the first user. The first user   will be an administrator. - For SAML, OAuth2 (non-Google), PAM or proxied authentication, the first user can be   created by logging into Posit Connect. The API cannot be used.  Once the first user is created, an API Key can be used to access this endpoint and create subsequent users. The [API Keys](../user/api-keys/) chapter of the Posit Connect User Guide explains how to create an API Key.  #### All Authentication Providers  - When &#x60;user_role&#x60; is not specified, it will default to the   role specified by the config setting   &#x60;Authorization.DefaultUserRole&#x60;.  #### SAML, OAuth2 (non-Google), PAM and Proxied Authentication  - An API Key must always be used. Users cannot use this   endpoint to create their own account. - Administrator access is always required to create accounts.  #### Password Authentication  - Users must confirm their account through an email. This   feature is unique to password authentication. - Administrator access is always required except for the first   created user.
  # @param user CreatePushUserRequest The new user values.
  # @return [User]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetCurrentUser", {
  # tests for GetCurrentUser
  # base path: /__api__
  # Get current user details
  # Get detailed information on the requesting user.
  # @return [User]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetUser", {
  # tests for GetUser
  # base path: /__api__
  # Get user details
  # Get detailed information on a specific user.  The &#x60;email&#x60; field is not populated for non-admins when &#x60;Server.HideEmailAddresses&#x60; is enabled.
  # @param guid character The user's GUID, or unique identifier  Example value = `6f300623-1e0c-48e6-a473-ddf630c0c0c3` using UUID [RFC4122](https://www.rfc-editor.org/rfc/rfc4122) format.
  # @return [User]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetUsers", {
  # tests for GetUsers
  # base path: /__api__
  # List or search for user details
  # This endpoint lists local users. When called with a prefix parameter, it searches for local users matching the prefix.  Results are sorted by first name, then last name, then username, then email. &#x60;prefix&#x60; searches are first sorted based on similarity to the prefix and then by first name, last name, username, email. The &#x60;prefix&#x60; can also be an exact match for the user&#39;s DN (for LDAP) or the auth provider&#39;s unique ID for the user, if any.  - Administrator access is required for filtering by   &#x60;account_status&#x60;. - The &#x60;email&#x60; field is not populated for non-admins when   &#x60;Server.HideEmailAddresses&#x60; is enabled. - When the user making the request is a viewer and   &#x60;Authorization.ViewersCanOnlySeeThemselves&#x60; is being used,   the results contain only the given user.  #### Pagination  This endpoint uses offset pagination (using page numbers). The [Offset Pagination](../cookbook/pagination/#offset-pagination) recipe in the Posit Connect API Cookbook has sample code for fetching multiple pages from a list endpoint.  Note that searching by &#x60;prefix&#x60; will always return the first page of results.
  # @param prefix character Filters users by prefix (username, first name, or last name). The filter is case insensitive. (optional)
  # @param user_role character Filter by user role. \"|\" represents logical OR. For example, `user_role=viewer|publisher` means users who are either a viewer or a publisher will be included in the result.  Note that for `user_role`, logical AND is also supported but always returns no results. For example, `user_role=viewer&user_role=publisher` tries to return users who are both viewers and publishers. (optional)
  # @param account_status character Filter by account status. \"|\" represents logical OR. For example, `account_status=locked|licensed` means users who are either locked or licensed. - `locked` - Users with a locked account. - `licensed` - Users regarded as licensed (unlocked and   recently active). - `inactive` - Users not locked and not recently active.  Note that for `account_status`, logical AND is also supported but always returns no results. For example, `account_status=locked&account_status=licensed` tries to return users who are both locked and licensed. (optional)
  # @param page_number integer The page to return relative to the given `page_size`. If `page_number` is 0 or negative, an error will be returned. (optional)
  # @param page_size integer The number of items to include in each page. This parameter is \"best effort\" since there may not be enough users to honor the request. If `page_size` is less than 1 or greater than 500, an error will be returned. (optional)
  # @param asc_order character Whether or not to return the users in ascending order, sorted by first name, last name, username, and email. (optional)
  # @return [Users]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("LockUser", {
  # tests for LockUser
  # base path: /__api__
  # Lock a user
  # This endpoint locks or unlocks a given user account.  - License limits are taken into account when unlocking a user. - Administrator access is required to access this endpoint. - Users are able to lock themselves.
  # @param guid character The user's GUID, or unique identifier  Example value = `6f300623-1e0c-48e6-a473-ddf630c0c0c3` using UUID [RFC4122](https://www.rfc-editor.org/rfc/rfc4122) format.
  # @param request LockUserRequest The lock request
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("SearchRemoteUsers", {
  # tests for SearchRemoteUsers
  # base path: /__api__
  # Search for user details from a remote provider
  # This endpoint is used to support operations against users who do not have an Posit Connect account, such as &lt;a href&#x3D;\&quot;#put-/v1/users\&quot;&gt;creating LDAP and OAuth2 with Google users&lt;/a&gt; See &lt;a href&#x3D;\&quot;#get-/v1/users\&quot;&gt;GET /v1/users&lt;/a&gt; for listing users.  This endpoint searches for users on Posit Connect and on your LDAP or OAuth2 with Google system.  Results are first sorted based on similarity to the &#x60;prefix&#x60; and then by first name, last name, username, and email.  - This endpoint can be used only by LDAP or OAuth2 with Google   authentication and will return an error otherwise. - Publisher or administrator access is required to access this   endpoint. - The &#x60;email&#x60; field is not populated for non-admins when   &#x60;Server.HideEmailAddresses&#x60; is enabled. - When the user making the request is a viewer and   &#x60;Authorization.ViewersCanOnlySeeThemselves&#x60; is being used,   the results contain only the given user.
  # @param prefix character Search users by prefix (username, first name, or last name). `prefix` is case insensitive.
  # @param limit integer The maximum number of users to include in the results. If `limit` is less than 1 or greater than 500, an error will be returned. (optional)
  # @return [RemoteSearchResults]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UpdateUser", {
  # tests for UpdateUser
  # base path: /__api__
  # Update a user
  # This endpoint updates a given user and returns the updated user properties. Note that it returns only the properties that can be modified by this endpoint.  If the authentication provider allows it:  - a user can change their own user properties. - another user&#39;s properties can be changed with administrator   access. - The configuration setting &#x60;Authorization.UserInfoEditableBy&#x60;   controls whether or not non-admins can edit their own properties.  #### Password Authentication  - Emails are required. - Changing an unconfirmed user&#39;s email will cause the   confirmation email to be resent to the new email.
  # @param guid character The user's GUID, or unique identifier  Example value = `6f300623-1e0c-48e6-a473-ddf630c0c0c3` using UUID [RFC4122](https://www.rfc-editor.org/rfc/rfc4122) format.
  # @param user UpdateUserRequest The new user values.
  # @return [EditableUser]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
