# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test JobItem")

model_instance <- JobItem$new()

test_that("id", {
  # tests for the property `id` (character)
  # The job identifier.

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("ppid", {
  # tests for the property `ppid` (character)
  # The job&#39;s parent process identifier.

  # uncomment below to test the property
  #expect_equal(model.instance$`ppid`, "EXPECTED_RESULT")
})

test_that("pid", {
  # tests for the property `pid` (character)
  # The job&#39;s process identifier.

  # uncomment below to test the property
  #expect_equal(model.instance$`pid`, "EXPECTED_RESULT")
})

test_that("key", {
  # tests for the property `key` (character)
  # The job&#39;s unique key identifier.

  # uncomment below to test the property
  #expect_equal(model.instance$`key`, "EXPECTED_RESULT")
})

test_that("remote_id", {
  # tests for the property `remote_id` (character)
  # The job&#39;s identifier for off-host execution configurations.

  # uncomment below to test the property
  #expect_equal(model.instance$`remote_id`, "EXPECTED_RESULT")
})

test_that("app_id", {
  # tests for the property `app_id` (character)
  # The job&#39;s parent content identifier

  # uncomment below to test the property
  #expect_equal(model.instance$`app_id`, "EXPECTED_RESULT")
})

test_that("variant_id", {
  # tests for the property `variant_id` (character)
  # The identifier of the variant owning this job.

  # uncomment below to test the property
  #expect_equal(model.instance$`variant_id`, "EXPECTED_RESULT")
})

test_that("bundle_id", {
  # tests for the property `bundle_id` (character)
  # The identifier of a content bundle linked to this job.

  # uncomment below to test the property
  #expect_equal(model.instance$`bundle_id`, "EXPECTED_RESULT")
})

test_that("start_time", {
  # tests for the property `start_time` (character)
  # The timestamp (RFC3339) indicating when this job started.

  # uncomment below to test the property
  #expect_equal(model.instance$`start_time`, "EXPECTED_RESULT")
})

test_that("end_time", {
  # tests for the property `end_time` (character)
  # The timestamp (RFC3339) indicating when this job finished.

  # uncomment below to test the property
  #expect_equal(model.instance$`end_time`, "EXPECTED_RESULT")
})

test_that("last_heartbeat_time", {
  # tests for the property `last_heartbeat_time` (character)
  # The timestamp (RFC3339) indicating the last time  this job was observed to be running.

  # uncomment below to test the property
  #expect_equal(model.instance$`last_heartbeat_time`, "EXPECTED_RESULT")
})

test_that("queued_time", {
  # tests for the property `queued_time` (character)
  # The timestamp (RFC3339) indicating when this job was added to the queue to be processed. Only scheduled reports will present a value for this field.

  # uncomment below to test the property
  #expect_equal(model.instance$`queued_time`, "EXPECTED_RESULT")
})

test_that("queue_name", {
  # tests for the property `queue_name` (character)
  # The name of the queue which processes the job. Only scheduled reports  will present a value for this field.

  # uncomment below to test the property
  #expect_equal(model.instance$`queue_name`, "EXPECTED_RESULT")
})

test_that("tag", {
  # tests for the property `tag` (character)
  # A tag to identify the nature of the job. It can be one of &#x60;unknown&#x60;, &#x60;build_report&#x60;, &#x60;build_site&#x60;, &#x60;build_jupyter&#x60;, &#x60;packrat_restore&#x60;, &#x60;python_restore&#x60;, &#x60;configure_report&#x60;, &#x60;run_app&#x60;, &#x60;run_api&#x60;, &#x60;run_tensorflow&#x60; (obsolete), &#x60;run_python_api&#x60;, &#x60;run_dash_app&#x60;, &#x60;run_streamlit&#x60;, &#x60;run_bokeh_app&#x60;, &#x60;run_fastapi_app&#x60;, &#x60;run_pyshiny_app&#x60;, &#x60;render_shiny&#x60;, &#x60;run_voila_app&#x60;, &#x60;testing&#x60;, &#x60;git&#x60;, &#x60;val_py_ext_pkg&#x60;, &#x60;val_r_ext_pkg&#x60;, &#x60;val_r_install&#x60;.

  # uncomment below to test the property
  #expect_equal(model.instance$`tag`, "EXPECTED_RESULT")
})

test_that("exit_code", {
  # tests for the property `exit_code` (integer)
  # The job&#39;s exit code. Present only when job is finished.

  # uncomment below to test the property
  #expect_equal(model.instance$`exit_code`, "EXPECTED_RESULT")
})

test_that("status", {
  # tests for the property `status` (integer)
  # The current status of the job. It can be one of Active: &#x60;0&#x60;, Finished: &#x60;1&#x60;, Finalized: &#x60;2&#x60;.

  # uncomment below to test the property
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

test_that("hostname", {
  # tests for the property `hostname` (character)
  # The name of the node which processes the job.

  # uncomment below to test the property
  #expect_equal(model.instance$`hostname`, "EXPECTED_RESULT")
})

test_that("cluster", {
  # tests for the property `cluster` (character)
  # The location where this content runs. Content running on the same server as Connect will have either a &#x60;null&#x60; value or the string &#x60;Local&#x60;. Gives the name of the cluster when run external to the Connect host.

  # uncomment below to test the property
  #expect_equal(model.instance$`cluster`, "EXPECTED_RESULT")
})

test_that("image", {
  # tests for the property `image` (character)
  # The location where this content runs. Content running on the same server as Connect will have either a &#x60;null&#x60; value or the string &#x60;Local&#x60;. References the name of the target image when content runs in a clustered environment such as Kubernetes.

  # uncomment below to test the property
  #expect_equal(model.instance$`image`, "EXPECTED_RESULT")
})

test_that("run_as", {
  # tests for the property `run_as` (character)
  # The UNIX user that executed this job.

  # uncomment below to test the property
  #expect_equal(model.instance$`run_as`, "EXPECTED_RESULT")
})
