# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Content")

model_instance <- Content$new()

test_that("guid", {
  # tests for the property `guid` (character)
  # The unique identifier of this content item.

  # uncomment below to test the property
  #expect_equal(model.instance$`guid`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # A simple, URL-friendly identifier. Allows alpha-numeric characters, hyphens (&#x60;\&quot;-\&quot;&#x60;), and underscores (&#x60;\&quot;_\&quot;&#x60;).

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("title", {
  # tests for the property `title` (character)
  # The title of this content.

  # uncomment below to test the property
  #expect_equal(model.instance$`title`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)
  # A rich description of this content.

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("access_type", {
  # tests for the property `access_type` (character)
  # Access type describes how this content manages its viewers. The value &#x60;all&#x60; is the most permissive; any visitor to Posit Connect will be able to view this content. The value &#x60;logged_in&#x60; indicates that all Posit Connect accounts may view the content. The &#x60;acl&#x60; value lets specifically enumerated users and groups view the content. Users configured as collaborators may always view content.

  # uncomment below to test the property
  #expect_equal(model.instance$`access_type`, "EXPECTED_RESULT")
})

test_that("connection_timeout", {
  # tests for the property `connection_timeout` (integer)
  # Maximum number of seconds allowed without data sent or received across a client connection. A value of &#x60;0&#x60; means connections will never time-out (not recommended). When &#x60;null&#x60;, the default &#x60;Scheduler.ConnectionTimeout&#x60; is used. Applies only to content types that are executed on demand.

  # uncomment below to test the property
  #expect_equal(model.instance$`connection_timeout`, "EXPECTED_RESULT")
})

test_that("read_timeout", {
  # tests for the property `read_timeout` (integer)
  # Maximum number of seconds allowed without data received from a client connection. A value of &#x60;0&#x60; means a lack of client (browser) interaction never causes the connection to close. When &#x60;null&#x60;, the default &#x60;Scheduler.ReadTimeout&#x60; is used. Applies only to content types that are executed on demand.

  # uncomment below to test the property
  #expect_equal(model.instance$`read_timeout`, "EXPECTED_RESULT")
})

test_that("init_timeout", {
  # tests for the property `init_timeout` (integer)
  # The maximum number of seconds allowed for an interactive application to start. Posit Connect must be able to connect to a newly launched application before this threshold has elapsed. When &#x60;null&#x60;, the default &#x60;Scheduler.InitTimeout&#x60; is used. Applies only to content types that are executed on demand.

  # uncomment below to test the property
  #expect_equal(model.instance$`init_timeout`, "EXPECTED_RESULT")
})

test_that("idle_timeout", {
  # tests for the property `idle_timeout` (integer)
  # The maximum number of seconds a worker process for an interactive application to remain alive after it goes idle (no active connections). When &#x60;null&#x60;, the default &#x60;Scheduler.IdleTimeout&#x60; is used. Applies only to content types that are executed on demand.

  # uncomment below to test the property
  #expect_equal(model.instance$`idle_timeout`, "EXPECTED_RESULT")
})

test_that("max_processes", {
  # tests for the property `max_processes` (integer)
  # Specifies the total number of concurrent processes allowed for a single interactive application. When &#x60;null&#x60;, the default &#x60;Scheduler.MaxProcesses&#x60; is used. Applies only to content types that are executed on demand.

  # uncomment below to test the property
  #expect_equal(model.instance$`max_processes`, "EXPECTED_RESULT")
})

test_that("min_processes", {
  # tests for the property `min_processes` (integer)
  # Specifies the minimum number of concurrent processes allowed for a single interactive application. When &#x60;null&#x60;, the default &#x60;Scheduler.MinProcesses&#x60; is used. Applies only to content types that are executed on demand.

  # uncomment below to test the property
  #expect_equal(model.instance$`min_processes`, "EXPECTED_RESULT")
})

test_that("max_conns_per_process", {
  # tests for the property `max_conns_per_process` (integer)
  # Specifies the maximum number of client connections allowed to an individual process. Incoming connections which will exceed this limit are routed to a new process or rejected. When &#x60;null&#x60;, the default &#x60;Scheduler.MaxConnsPerProcess&#x60; is used. Applies only to content types that are executed on demand.

  # uncomment below to test the property
  #expect_equal(model.instance$`max_conns_per_process`, "EXPECTED_RESULT")
})

test_that("load_factor", {
  # tests for the property `load_factor` (numeric)
  # Controls how aggressively new processes are spawned. When &#x60;null&#x60;, the default &#x60;Scheduler.LoadFactor&#x60; is used. Applies only to content types that are executed on demand.

  # uncomment below to test the property
  #expect_equal(model.instance$`load_factor`, "EXPECTED_RESULT")
})

test_that("cpu_request", {
  # tests for the property `cpu_request` (numeric)
  # The minimum amount of compute power this content needs when executing or rendering, expressed in [\&quot;CPU Units\&quot;](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#meaning-of-cpu), where 1.0 unit is equivalent to 1 physical or virtual core. Fractional values are allowed. This is used when running in an off-host execution configuration to determine where the content should be run. When &#x60;null&#x60;, the default &#x60;Scheduler.CPURequest&#x60; is used.

  # uncomment below to test the property
  #expect_equal(model.instance$`cpu_request`, "EXPECTED_RESULT")
})

test_that("cpu_limit", {
  # tests for the property `cpu_limit` (numeric)
  # The maximum amount of compute power this content will be allowed to consume when executing or rendering, expressed in [\&quot;CPU Units\&quot;](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#meaning-of-cpu), where 1.0 unit is equivalent to 1 physical or virtual core. Fractional values are allowed. This is used when running in an off-host execution configuration. If the process tries to use more CPU than allowed, it will be throttled. When &#x60;null&#x60;, the default &#x60;Scheduler.CPULimit&#x60; is used.

  # uncomment below to test the property
  #expect_equal(model.instance$`cpu_limit`, "EXPECTED_RESULT")
})

test_that("memory_request", {
  # tests for the property `memory_request` (integer)
  # The minimum amount of RAM this content needs when executing or rendering, expressed in bytes. This is used when running in an off-host execution configuration to determine where the content should be run. When &#x60;null&#x60;, the default &#x60;Scheduler.MemoryRequest&#x60; is used.

  # uncomment below to test the property
  #expect_equal(model.instance$`memory_request`, "EXPECTED_RESULT")
})

test_that("memory_limit", {
  # tests for the property `memory_limit` (integer)
  # The maximum amount of RAM this content will be allowed to consume when executing or rendering, expressed in bytes. If the process tries to use more memory than allowed, it will be terminated. When &#x60;null&#x60;, the default &#x60;Scheduler.MemoryLimit&#x60; is used.

  # uncomment below to test the property
  #expect_equal(model.instance$`memory_limit`, "EXPECTED_RESULT")
})

test_that("created_time", {
  # tests for the property `created_time` (character)
  # The timestamp (RFC3339) indicating when this content was created.

  # uncomment below to test the property
  #expect_equal(model.instance$`created_time`, "EXPECTED_RESULT")
})

test_that("last_deployed_time", {
  # tests for the property `last_deployed_time` (character)
  # The timestamp (RFC3339) indicating when this content last had a successful bundle deployment performed.

  # uncomment below to test the property
  #expect_equal(model.instance$`last_deployed_time`, "EXPECTED_RESULT")
})

test_that("bundle_id", {
  # tests for the property `bundle_id` (character)
  # The identifier for the active deployment bundle. Automatically assigned upon the successful deployment of that bundle.

  # uncomment below to test the property
  #expect_equal(model.instance$`bundle_id`, "EXPECTED_RESULT")
})

test_that("app_mode", {
  # tests for the property `app_mode` (character)
  # The runtime model for this content. Has a value of &#x60;unknown&#x60; before data is deployed to this item. Automatically assigned upon the first successful bundle deployment.  Valid values are:  * &#x60;api&#x60; - R code defining a [Plumber API](https://www.rplumber.io/). * &#x60;jupyter-static&#x60; - A [Jupyter Notebook](https://jupyter-notebook.readthedocs.io/en/stable/). * &#x60;python-api&#x60; - Python code defining a WSGI API (such as [Flask](https://palletsprojects.com/p/flask/)) * &#x60;python-bokeh&#x60; - Python code defining a [Bokeh application](https://bokeh.org/). * &#x60;python-dash&#x60; - Python code defining a [Dash application](https://dash.plotly.com/). * &#x60;python-fastapi&#x60; - Python code defining an ASGI API (such as [FastAPI](https://fastapi.tiangolo.com/)) * &#x60;python-streamlit&#x60; - Python code defining a [Streamlit application](https://streamlit.io/). * &#x60;python-shiny&#x60; - Python code defining a [Shiny application](https://shiny.rstudio.com/py/). * &#x60;quarto-shiny&#x60; - A [Quarto](https://quarto.org/) document with a Shiny runtime. * &#x60;quarto-static&#x60; - A [Quarto](https://quarto.org/) document or site. * &#x60;rmd-shiny&#x60; - An [R Markdown](https://rmarkdown.rstudio.com/) document with a Shiny runtime. * &#x60;rmd-static&#x60; - An [R Markdown](https://rmarkdown.rstudio.com/) document or site. * &#x60;shiny&#x60; - R code defining a [Shiny application](https://shiny.rstudio.com/). * &#x60;static&#x60; - Content deployed without source; often HTML and plots. * &#x60;tensorflow-saved-model&#x60; - A TensorFlow Model API (obsolete). * &#x60;unknown&#x60; - No known runtime model.

  # uncomment below to test the property
  #expect_equal(model.instance$`app_mode`, "EXPECTED_RESULT")
})

test_that("content_category", {
  # tests for the property `content_category` (character)
  # Describes the specialization of the content runtime model. Automatically assigned upon the first successful bundle deployment.  The &#x60;content_category&#x60; field refines the type of content specified by &#x60;app_mode&#x60;. It is empty by default. The rsconnect R package may assign a value when analyzing your content and building its manifest and bundle. Plots (images created in the RStudio IDE and presented in the \&quot;Plots\&quot; pane) have an &#x60;app_mode&#x60; of &#x60;static&#x60; and receive a &#x60;content_category&#x60; of &#x60;plot&#x60; to distinguish them from other HTML documents. Pinned static data sets have an &#x60;app_mode&#x60; of &#x60;static&#x60; and a &#x60;content_category&#x60; of &#x60;pin&#x60;. Multi-document R Markdown sites have an &#x60;app_mode&#x60; of &#x60;rmd-static&#x60; and a &#x60;content_category&#x60; of &#x60;site&#x60;.

  # uncomment below to test the property
  #expect_equal(model.instance$`content_category`, "EXPECTED_RESULT")
})

test_that("parameterized", {
  # tests for the property `parameterized` (character)
  # True when R Markdown rendered content allows parameter configuration. Automatically assigned upon the first successful bundle deployment. Applies only to content with an &#x60;app_mode&#x60; of &#x60;rmd-static&#x60;.

  # uncomment below to test the property
  #expect_equal(model.instance$`parameterized`, "EXPECTED_RESULT")
})

test_that("cluster_name", {
  # tests for the property `cluster_name` (character)
  # The location where this content runs. Content running on the same server as Connect will have either a &#x60;null&#x60; value or the string \&quot;Local\&quot;. Gives the name of the cluster when run external to the Connect host. A &#x60;null&#x60; value is returned when the client does not have sufficient rights to see this information.

  # uncomment below to test the property
  #expect_equal(model.instance$`cluster_name`, "EXPECTED_RESULT")
})

test_that("image_name", {
  # tests for the property `image_name` (character)
  # The location where content this content runs. Content running on the same server as Connect will have either a &#x60;null&#x60; value or the string \&quot;Local\&quot;. References the name of the target image when content runs in a clustered environment such as Kubernetes. A &#x60;null&#x60; value is returned when the client does not have sufficient rights to see this information.

  # uncomment below to test the property
  #expect_equal(model.instance$`image_name`, "EXPECTED_RESULT")
})

test_that("default_image_name", {
  # tests for the property `default_image_name` (character)
  # The default image that will be used when none is defined by the bundle&#39;s manifest. A specific image may be selected by setting the &#x60;environment.image&#x60; field in the manifest. If no image is selected by the manifest file, then the &#x60;default_image_name&#x60; is used. If a target image is not defined by the manifest, and no &#x60;default_image_name&#x60; is configured, then Connect will select an image from the list of configured execution environments.  A &#x60;null&#x60; value is returned when the client does not have sufficient rights to see this information.  Use the &#x60;/v1/environments&#x60; API endpoints to determine which environments are available for content execution.

  # uncomment below to test the property
  #expect_equal(model.instance$`default_image_name`, "EXPECTED_RESULT")
})

test_that("default_r_environment_management", {
  # tests for the property `default_r_environment_management` (character)
  # Indicates whether or not Connect should create and manage an R environment (installing required packages) for this content. When &#x60;null&#x60;, Connect makes this determination based on the server configuration.  A &#x60;null&#x60; value is also returned when the client does not have sufficient rights to see this information.  This value is ignored if the server setting &#x60;Applications.DefaultEnvironmentManagementSelection&#x60; is disabled.

  # uncomment below to test the property
  #expect_equal(model.instance$`default_r_environment_management`, "EXPECTED_RESULT")
})

test_that("default_py_environment_management", {
  # tests for the property `default_py_environment_management` (character)
  # Indicates whether or not Connect should create and manage a Python environment (installing required packages) for this content. When &#x60;null&#x60;, Connect makes this determination based on the server configuration.  A &#x60;null&#x60; value is also returned when the client does not have sufficient rights to see this information.  This value is ignored if the server setting &#x60;Applications.DefaultEnvironmentManagementSelection&#x60; is disabled.

  # uncomment below to test the property
  #expect_equal(model.instance$`default_py_environment_management`, "EXPECTED_RESULT")
})

test_that("service_account_name", {
  # tests for the property `service_account_name` (character)
  # The name of the Kubernetes service account that is used to run a particular piece of content.  It must adhere to valid Kubernetes service account naming rules.  Connect must be configured to run with &#x60;Launcher.Enabled &#x3D; true&#x60;, &#x60;Launcher.Kubernetes &#x3D; true&#x60; and &#x60;Launcher.KubernetesContentServiceAccountSelection &#x3D; true&#x60;  for this value to be applied. It will have precedence over the &#x60;Launcher.KubernetesDefaultServiceAccount&#x60; that may be set in the configuration for Connect.  If this value is defined and Connect is configured with &#x60;Launcher.KubernetesContentServiceAccountSelection &#x3D; false&#x60; an error will be returned.  Only administrators and publishers can view this value. Only administrators can set or change this value.

  # uncomment below to test the property
  #expect_equal(model.instance$`service_account_name`, "EXPECTED_RESULT")
})

test_that("r_version", {
  # tests for the property `r_version` (character)
  # The of R interpreter associated with this content. A &#x60;null&#x60; value represents that R is not used by this content, that the content has not been prepared for execution, or that the client does not have sufficient rights to see this information. Automatically assigned upon the successful deployment of a bundle.

  # uncomment below to test the property
  #expect_equal(model.instance$`r_version`, "EXPECTED_RESULT")
})

test_that("r_environment_management", {
  # tests for the property `r_environment_management` (character)
  # Indicates whether or not Connect is managing an R environment and has installed the required packages for this content. A &#x60;null&#x60; value represents that R is not used by this content, that the content has not been prepared for execution, or that the client does not have sufficient rights to see this information. Automatically assigned upon the successful deployment of a bundle.

  # uncomment below to test the property
  #expect_equal(model.instance$`r_environment_management`, "EXPECTED_RESULT")
})

test_that("py_version", {
  # tests for the property `py_version` (character)
  # The version of Python associated with this content. A &#x60;null&#x60; value represents that Python is not used by this content, that the content has not been prepared for execution, or that the client does not have sufficient rights to see this information. Automatically assigned upon the successful deployment of a bundle.

  # uncomment below to test the property
  #expect_equal(model.instance$`py_version`, "EXPECTED_RESULT")
})

test_that("py_environment_management", {
  # tests for the property `py_environment_management` (character)
  # Indicates whether or not Connect is managing a Python environment and has installed the required packages for this content. A &#x60;null&#x60; value represents that Python is not used by this content, that the content has not been prepared for execution, or that the client does not have sufficient rights to see this information. Automatically assigned upon the successful deployment of a bundle.

  # uncomment below to test the property
  #expect_equal(model.instance$`py_environment_management`, "EXPECTED_RESULT")
})

test_that("quarto_version", {
  # tests for the property `quarto_version` (character)
  # The version of Quarto associated with this content. A &#x60;null&#x60; represents that Quarto is not used by this content, that the content has not been prepared for execution, or that the client does not have sufficient rights to see this information. Automatically assigned upon the successful deployment of a bundle.

  # uncomment below to test the property
  #expect_equal(model.instance$`quarto_version`, "EXPECTED_RESULT")
})

test_that("run_as", {
  # tests for the property `run_as` (character)
  # The UNIX user that executes this content. When &#x60;null&#x60;, the default &#x60;Applications.RunAs&#x60; is used. Applies only to executable content types - not &#x60;static&#x60;.  Only administrators can change this value.

  # uncomment below to test the property
  #expect_equal(model.instance$`run_as`, "EXPECTED_RESULT")
})

test_that("run_as_current_user", {
  # tests for the property `run_as_current_user` (character)
  # Indicates that Connect should run processes for this content item under the Unix account of the user who visits it. Content accessed anonymously will continue to run as the specified &#x60;run_as&#x60; user.  Connect must be configured to use PAM authentication with the server settings &#x60;Applications.RunAsCurrentUser &#x3D; true&#x60; and &#x60;PAM.ForwardPassword &#x3D; true&#x60;. This setting has no effect for other authentication types.  This setting only applies to application content types (Shiny, Dash, Streamlit, and Bokeh).  Only administrators can change this value.

  # uncomment below to test the property
  #expect_equal(model.instance$`run_as_current_user`, "EXPECTED_RESULT")
})

test_that("owner_guid", {
  # tests for the property `owner_guid` (character)
  # The unique identifier of the user who created this content item. Automatically assigned when the content is created.

  # uncomment below to test the property
  #expect_equal(model.instance$`owner_guid`, "EXPECTED_RESULT")
})

test_that("content_url", {
  # tests for the property `content_url` (character)
  # The URL associated with this content. Computed from the associated vanity URL or GUID for this content.

  # uncomment below to test the property
  #expect_equal(model.instance$`content_url`, "EXPECTED_RESULT")
})

test_that("dashboard_url", {
  # tests for the property `dashboard_url` (character)
  # The URL within the Connect dashboard where this content can be configured. Computed from the GUID for this content.

  # uncomment below to test the property
  #expect_equal(model.instance$`dashboard_url`, "EXPECTED_RESULT")
})

test_that("role", {
  # tests for the property `role` (character)
  # The relationship of the accessing user to this content. A value of &#x60;owner&#x60; is returned for the content owner. &#x60;editor&#x60; indicates a collaborator. The &#x60;viewer&#x60; value is given to users who are permitted to view the content. A &#x60;none&#x60; role is returned for administrators who cannot view the content but are permitted to view its configuration. Computed at the time of the request.

  # uncomment below to test the property
  #expect_equal(model.instance$`role`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (character)
  # The internal numeric identifier of this content item.

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})
