# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AuditPager")

model_instance <- AuditPager$new()

test_that("cursors", {
  # tests for the property `cursors` (AuditPagerCursors)

  # uncomment below to test the property
  #expect_equal(model.instance$`cursors`, "EXPECTED_RESULT")
})

test_that("first", {
  # tests for the property `first` (character)
  # A full URL of the first page of results.  It will be &#x60;null&#x60; if the current response represents the first page of results.

  # uncomment below to test the property
  #expect_equal(model.instance$`first`, "EXPECTED_RESULT")
})

test_that("previous", {
  # tests for the property `previous` (character)
  # A full URL of the previous page of results when the curent request was made.  It will be &#x60;null&#x60; if the current response represents the first page of results.

  # uncomment below to test the property
  #expect_equal(model.instance$`previous`, "EXPECTED_RESULT")
})

test_that("next", {
  # tests for the property `next` (character)
  # A full URL of the next page of results when the current request was made.  It will be &#x60;null&#x60; if the current response represents the last page of results.

  # uncomment below to test the property
  #expect_equal(model.instance$`next`, "EXPECTED_RESULT")
})

test_that("last", {
  # tests for the property `last` (character)
  # A full URL of the last page of results.  It will be &#x60;null&#x60; if the current response represents the last page of results.

  # uncomment below to test the property
  #expect_equal(model.instance$`last`, "EXPECTED_RESULT")
})
