# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BundleMetadata")

model_instance <- BundleMetadata$new()

test_that("source", {
  # tests for the property `source` (character)
  # Source for this bundle. &#x60;null&#x60; for uploaded bundles, or &#x60;git&#x60; for bundles fetched from a git repository.

  # uncomment below to test the property
  #expect_equal(model.instance$`source`, "EXPECTED_RESULT")
})

test_that("source_repo", {
  # tests for the property `source_repo` (character)
  # Git repository URL for this bundle. &#x60;null&#x60; for bundles that were not fetched from a git repository.

  # uncomment below to test the property
  #expect_equal(model.instance$`source_repo`, "EXPECTED_RESULT")
})

test_that("source_branch", {
  # tests for the property `source_branch` (character)
  # Git repository branch name for this bundle. &#x60;null&#x60; for bundles that were not fetched from a git repository.

  # uncomment below to test the property
  #expect_equal(model.instance$`source_branch`, "EXPECTED_RESULT")
})

test_that("source_commit", {
  # tests for the property `source_commit` (character)
  # Git commit ID (hash) for this bundle. &#x60;null&#x60; for bundles that were not fetched from a git repository.

  # uncomment below to test the property
  #expect_equal(model.instance$`source_commit`, "EXPECTED_RESULT")
})

test_that("archive_md5", {
  # tests for the property `archive_md5` (character)
  # MD5 hash of the archive file for this bundle. &#x60;null&#x60; for bundles uploaded before this field was added.

  # uncomment below to test the property
  #expect_equal(model.instance$`archive_md5`, "EXPECTED_RESULT")
})

test_that("archive_sha1", {
  # tests for the property `archive_sha1` (character)
  # SHA1 hash of the archive file for this bundle. &#x60;null&#x60; for bundles uploaded before this field was added.

  # uncomment below to test the property
  #expect_equal(model.instance$`archive_sha1`, "EXPECTED_RESULT")
})
