# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test LogEntry")

model_instance <- LogEntry$new()

test_that("source", {
  # tests for the property `source` (character)
  # The source of the log entry. &#x60;stdout&#x60; or &#x60;stderr&#x60;.

  # uncomment below to test the property
  #expect_equal(model.instance$`source`, "EXPECTED_RESULT")
})

test_that("timestamp", {
  # tests for the property `timestamp` (character)
  # The timestamp (RFC3339) indicating when this log entry was recorded.

  # uncomment below to test the property
  #expect_equal(model.instance$`timestamp`, "EXPECTED_RESULT")
})

test_that("data", {
  # tests for the property `data` (character)
  # The log entry content.

  # uncomment below to test the property
  #expect_equal(model.instance$`data`, "EXPECTED_RESULT")
})
