# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test VanityURLsApi")

api_instance <- VanityURLsApi$new()

test_that("DeleteVanity", {
  # tests for DeleteVanity
  # base path: /__api__
  # Delete vanity URL
  # Delete the vanity URL for this content.  If &#x60;Authorization.PublishersCanManageVanities&#x60; is &#x60;true&#x60;, publishers can delete the vanity URL for content items that they have permission to change. Otherwise, administrator permissions are required.
  # @param guid character The unique identifier of the desired content item.
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetVanity", {
  # tests for GetVanity
  # base path: /__api__
  # Get vanity URL
  # Get the vanity URL, if any, defined for this content. If the content item has a vanity URL, it is returned. If there is no vanity URL for this content, a 404 status is returned.  Administrators can get the vanity URL for any content item. Any authenticated user who is authorized to view the content can get the vanity URL.
  # @param guid character The unique identifier of the desired content item.
  # @return [GetVanity200Response]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListVanities", {
  # tests for ListVanities
  # base path: /__api__
  # List vanity URLs
  # List all defined vanity URLs.  You must have administrator privileges to perform this action.
  # @return [array[ListVanities200ResponseInner]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("SetVanity", {
  # tests for SetVanity
  # base path: /__api__
  # Set vanity URL
  # Set the vanity URL for this content item.  A vanity URL path must meet certain requirements:  *   It must consist of alphanumeric characters, hyphens, underscores,     and slashes.  *   It cannot be a reserved path such as the root path &#x60;/&#x60;, or a path     beginning with &#x60;/__&#x60;.      *   The following path prefixes are prohibited:      * &#x60;/__&#x60;     * &#x60;/favicon.ico&#x60;     * &#x60;/connect&#x60;     * &#x60;/apps&#x60;     * &#x60;/users&#x60;     * &#x60;/groups&#x60;     * &#x60;/setpassword&#x60;     * &#x60;/user-completion&#x60;     * &#x60;/confirm&#x60;     * &#x60;/recent&#x60;     * &#x60;/reports&#x60;     * &#x60;/plots&#x60;     * &#x60;/unpublished&#x60;     * &#x60;/settings&#x60;     * &#x60;/metrics&#x60;     * &#x60;/tokens&#x60;     * &#x60;/help&#x60;     * &#x60;/login&#x60;     * &#x60;/welcome&#x60;     * &#x60;/register&#x60;     * &#x60;/resetpassword&#x60;     * &#x60;/content&#x60;     * _The custom location for the Connect dashboard, configured by [&#x60;Server.DashboardPath&#x60;](../appendix/configuration/#Server.DashboardPath)._  *   It cannot be an ancestor or descendant of an existing vanity URL     path. For example, if the vanity path &#x60;/a/b/&#x60; exists, you cannot     add &#x60;/a/&#x60; or &#x60;/a/b/c/&#x60;.  If &#x60;Authorization.PublishersCanManageVanities&#x60; is &#x60;true&#x60;, publishers can set the vanity URL for content items that they have permission to change. Otherwise, administrator permissions are required.  You can reassign an existing vanity URL to a different content item, if you are an administrator or collaborator/owner of both content items. You must set the &#x60;force&#x60; parameter to &#x60;true&#x60; to reassign a URL. An error will be returned if &#x60;force&#x60; is &#x60;false&#x60; and the URL already exists.
  # @param guid character The unique identifier of the desired content item.
  # @param vanity SetVanityRequest The vanity URL definition to apply to this content item.
  # @return [SetVanity200Response]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
