# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AuditLogsApi")

api_instance <- AuditLogsApi$new()

test_that("GetAuditLogs", {
  # tests for GetAuditLogs
  # base path: /__api__
  # Get audit logs
  # This endpoint returns a portion of the audit logs, as well as paging information that can be used to navigate the audit log results.  This endpoint requires administrator access.  This endpoint uses keyset pagination. The [Keyset Pagination](../cookbook/pagination/#keyset-pagination) recipe in the Posit Connect API Cookbook has example code for fetching multiple pages.
  # @param limit integer Number of logs to return. The minimum supported value is 1 and maximum supported value is 500. Note that `limit` is a \"best effort\" request since there may not be enough logs to satisfy the limit. (optional)
  # @param previous character Gets the previous page of audit logs relative to the given id. (optional)
  # @param var_next character Gets the next page of audit logs relative to the given id. (optional)
  # @param asc_order character Whether the audit logs should be listed in ascending order (optional)
  # @return [AuditLogs]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
