# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CreateTagRequest")

model_instance <- CreateTagRequest$new()

test_that("name", {
  # tests for the property `name` (character)
  # The name of the tag. Tags under the same parent must have a unique name and cannot be longer than 255 characters.

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("parent_id", {
  # tests for the property `parent_id` (character)
  # The identifier for the parent tag. If there is no parent_id, the tag will be a top-level tag.

  # uncomment below to test the property
  #expect_equal(model.instance$`parent_id`, "EXPECTED_RESULT")
})
