# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UpdateUserRequest")

model_instance <- UpdateUserRequest$new()

test_that("email", {
  # tests for the property `email` (character)
  # The user&#39;s new email.

  # uncomment below to test the property
  #expect_equal(model.instance$`email`, "EXPECTED_RESULT")
})

test_that("username", {
  # tests for the property `username` (character)
  # The user&#39;s new username

  # uncomment below to test the property
  #expect_equal(model.instance$`username`, "EXPECTED_RESULT")
})

test_that("first_name", {
  # tests for the property `first_name` (character)
  # The user&#39;s new first name

  # uncomment below to test the property
  #expect_equal(model.instance$`first_name`, "EXPECTED_RESULT")
})

test_that("last_name", {
  # tests for the property `last_name` (character)
  # The user&#39;s new last name

  # uncomment below to test the property
  #expect_equal(model.instance$`last_name`, "EXPECTED_RESULT")
})

test_that("user_role", {
  # tests for the property `user_role` (character)
  # The user&#39;s new role. Note that you can only downgrade yourself. Administrators can change other users&#39; roles to any valid role.

  # uncomment below to test the property
  #expect_equal(model.instance$`user_role`, "EXPECTED_RESULT")
})
