# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test GroupOwnershipPermission")

model_instance <- GroupOwnershipPermission$new()

test_that("principal_guid", {
  # tests for the property `principal_guid` (character)
  # The identifier of the principal (user or group) with access to the content.

  # uncomment below to test the property
  #expect_equal(model.instance$`principal_guid`, "EXPECTED_RESULT")
})

test_that("principal_name", {
  # tests for the property `principal_name` (character)
  # The name of the principal (user or group) with access to the content.

  # uncomment below to test the property
  #expect_equal(model.instance$`principal_name`, "EXPECTED_RESULT")
})

test_that("principal_role", {
  # tests for the property `principal_role` (character)
  # The role of the principal (user or group) with access to the content.

  # uncomment below to test the property
  #expect_equal(model.instance$`principal_role`, "EXPECTED_RESULT")
})

test_that("principal_type", {
  # tests for the property `principal_type` (character)
  # The type of the principal (user or group) with access to the content.

  # uncomment below to test the property
  #expect_equal(model.instance$`principal_type`, "EXPECTED_RESULT")
})
