# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BootstrapV1ExperimentalApi")

api_instance <- BootstrapV1ExperimentalApi$new()

test_that("Bootstrap", {
  # tests for Bootstrap
  # base path: /__api__
  # Create first admininistrator and API key
  # This endpoint creates an initial admininistrator user, provisions an API key for the initial administrator, and returns the API key. This endpoint only functions for installations with no pre-existing users.
  # @return [BootstrapSuccess]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
