# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ContentV1ExperimentalApi")

api_instance <- ContentV1ExperimentalApi$new()

test_that("CreateContent", {
  # tests for CreateContent
  # base path: /__api__
  # Create content item
  # Create a new content item.  Authenticated access from a user having either \&quot;publisher\&quot; or \&quot;administrator\&quot; role is allowed. All other clients are rejected.
  # @param content CreateContentRequest1 The request body required when creating a new content item.
  # @return [ContentV1Exp]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeleteContent", {
  # tests for DeleteContent
  # base path: /__api__
  # Delete content
  # Delete a specific content item.  On-disk data and database records are removed as a consequence of this call.
  # @param guid character The unique identifier of the desired content item.
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeployContentBundle", {
  # tests for DeployContentBundle
  # base path: /__api__
  # Deploy deployment bundle
  # Deploy (activate) a deployment bundle.  Deployment requests spawn an asynchronous task to make your previously uploaded data available for serving. The workflow applied to the bundled files varies depending on the type of content.  Executable content has its environment reconstructed. This includes using the packrat R package to install R package dependencies.  Documents (R Markdown reports, Jupyter Notebooks) are rendered and the result made available.  Interactive content (Shiny applications, Plumber APIs) available to be launched on the next client visit.  The deployment workflow for static content (HTML, plots) is lighter-weight than for executable content. File time-stamps are updated to ensure that browsers do not cache previous results and instead see the newly promoted files.  The response from this endpoint includes a task identifier. Poll the &lt;a href&#x3D;\&quot;#get-/v1/experimental/tasks/-id-\&quot;&gt;GET /v1/experimental/tasks/{id}&lt;/a&gt; endpoint to track the progress of this task.
  # @param guid character The unique identifier of the desired content item.
  # @param instructions DeployContentBundleRequest1 The request body when requesting the deployment of a bundle. (optional)
  # @return [DeployContentBundle200Response]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetContent", {
  # tests for GetContent
  # base path: /__api__
  # Get content details
  # Get detailed information about a specific content item.  Unauthenticated clients are rejected regardless of the content access type.  Authorized, non-administrator clients without viewership rights to this content are rejected.  Authorized, administrator clients without viewership rights are permitted to obtain information about this content. The computed &#x60;role&#x60; for these users will be &#x60;none&#x60;, representing that these users cannot view the content itself.  Authorized clients with viewership (or collaborator) rights are permitted to obtain information about this content. The computed &#x60;role&#x60; for these users will reflect the level of access.  Information about the target environment is populated for users with \&quot;publisher\&quot; and \&quot;administrator\&quot; role; it is suppressed for viewers.
  # @param guid character The unique identifier of the desired content item.
  # @return [ContentV1Exp]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UpdateContent", {
  # tests for UpdateContent
  # base path: /__api__
  # Update content
  # Update fields for a specific content item.  Authenticated access from a user having either \&quot;publisher\&quot; or \&quot;administrator\&quot; role is allowed. All other clients are rejected.  Authorized clients with collaborator or administrator rights are permitted to modify content item fields.
  # @param guid character The unique identifier of the desired content item.
  # @param content UpdateContentRequest1 The request body required when creating a new content item.
  # @return [ContentV1Exp]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UploadContentBundle", {
  # tests for UploadContentBundle
  # base path: /__api__
  # Upload deployment bundle
  # Upload a new deployment bundle.  Upload a compressed &#x60;tar&#x60; archive containing code/data that represent one deployment of this content. Bundles must be &#x60;gzip&#x60; compressed &#x60;tar&#x60; archives.  All deployment bundles include a &#x60;manifest.json&#x60; describing the contained files and their runtime dependencies.  A bundle for a Shiny application include an &#x60;app.R&#x60; or &#x60;ui.R&#x60; and &#x60;server.R&#x60;, and any images or data files required by the application.  An R Markdown document bundle includes the &#x60;index.Rmd&#x60; file along with any R scripts and data files needed to render the report.  Bundles containing HTML content would include the CSS, Javascript, and images required by that document.  The archive paths for the &#x60;manifest.json&#x60; file and primary source files like &#x60;app.R&#x60; or &#x60;index.Rmd&#x60; must not specify a directory structure. Directories may be used for secondary data and scripts.  Here is how you might use &#x60;tar&#x60; to create an archive for a Shiny application. It includes the manifest, the application, and an image.  &#x60;&#x60;&#x60;bash tar zcf bundle.tar.gz ./manifest.json ./app.R ./www/logo.png &#x60;&#x60;&#x60;  Here is another example of creating a bundle for that same application but from its parent directory. The Shiny application is in a &#x60;sales-analyzer&#x60; sub-directory.  &#x60;&#x60;&#x60;bash tar -C sales-analyzer zcf bundle.tar.gz . &#x60;&#x60;&#x60;  Both &#x60;tar&#x60; commands will produce an archive with the &#x60;manifest.json&#x60; and &#x60;app.R&#x60; at the top-most level.  Publishers with collaborator rights to this content (including the owner) are permitted to upload deployment bundles. Users without these rights are rejected.  Administrators must be a collaborator for a content item before they receive upload rights.
  # @param guid character The unique identifier of the desired content item.
  # @param archive data.frame A `gzip` compressed `tar` archive file.
  # @param x_content_checksum character The Base64-encoded MD5 sum of the archive file. (optional)
  # @return [UploadContentBundle200Response]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
